import Solcore.Syntax.Parser.PublicSingleRecoveryOutputProperties
import Solcore.Syntax.Parser.UnexpectedDiagnosticCascadeProperties
import Solcore.Syntax.Parser.SourceFileBoundaryStopTraceProperties
import Solcore.Syntax.Parser.PublicPragmaNameRejectionOutputProperties
import Solcore.Syntax.Parser.ParseDiagnosticCascadeProperties
import Solcore.Syntax.Parser.IdentifierTraceProperties
import Solcore.Syntax.Parser.ExactTokenPrimitiveRejectionTraceProperties
import Solcore.Syntax.Parser.SourceFileSingleSuccessTraceProperties
import Solcore.Syntax.DeclarativeIdentifierCascadeProperties
import Solcore.Syntax.Parser.PublicPragmaSuccessOutputProperties
import Solcore.Syntax.Parser.PublicEmptyTokensOutputProperties
import Solcore.Syntax.Parser.TransactionalChoiceDiagnosticTraceProperties
import Solcore.Syntax.Parser.ParseDiagnosticCascadeStabilityProperties
import Solcore.Syntax.Parser.PublicPragmaSequenceOutputProperties
import Solcore.Syntax.Parser.PublicPragmaRejectionOutputProperties
import Solcore.Syntax.DeclarativePragmaRejectionCascadeProperties
import Solcore.Syntax.Parser.PublicPragmaPrefixBoundaryOutputProperties
import Solcore.Syntax.DeclarativeIsolatedBlockTraceProperties
import Solcore.Syntax.Parser.IsolatedBlockTraceCompletenessProperties
import Solcore.Syntax.DeclarativeCoreBlockTailCascadeProperties
import Solcore.Syntax.Parser.CoreBlockClosingTraceProperties
import Solcore.Syntax.DeclarativeCoreBlockTraceExactnessProperties
import Solcore.Syntax.DeclarativeCoreBlockCascadeProperties
import Solcore.Syntax.Parser.CoreBlockIsolationTraceProperties
import Solcore.Syntax.DeclarativeTerminatedControlTraceExactnessProperties
import Solcore.Syntax.Parser.ControlLeafDiagnosticTraceProperties
import Solcore.Syntax.DeclarativeReturnStatementTraceExactnessProperties
import Solcore.Syntax.Parser.ReturnStatementSuccessTraceProperties
import Solcore.Syntax.Parser.ReturnStatementRejectionTraceCompletenessProperties
import Solcore.Syntax.DeclarativeLiteralExpressionTraceExactnessProperties
import Solcore.Syntax.Parser.BooleanIdentifierRejectionTraceProperties
import Solcore.Syntax.Parser.LiteralExpressionTraceProperties
import Solcore.Syntax.Parser.BlockStatementTraceProperties
import Solcore.Syntax.Parser.IdentifierExpressionTraceProperties
import Solcore.Syntax.DeclarativeExpressionNameTraceProtectionProperties
import Solcore.Syntax.DeclarativeRejectionTraceProtectionProperties
import Solcore.Syntax.DeclarativeDelimitedNoTrailingTraceOutcomeProperties
import Solcore.Syntax.DeclarativeDelimitedNoTrailingTraceProtectionProperties
import Solcore.Syntax.Parser.DelimitedNoTrailingTraceContextProperties
import Solcore.Syntax.Parser.DelimitedNoTrailingRejectionTraceCorrespondenceProperties
import Solcore.Syntax.Parser.DelimitedNoTrailingTailRejectionTraceCorrespondenceProperties
import Solcore.Syntax.DeclarativeArrayLiteralTraceProperties
import Solcore.Syntax.Parser.ArrayLiteralTraceProperties
import Solcore.Syntax.DeclarativeDotConstructorTraceOutcomeProperties
import Solcore.Syntax.DeclarativeDotConstructorTraceProtectionProperties
import Solcore.Syntax.DeclarativeDotConstructorRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.DotConstructorSuccessTraceProperties
import Solcore.Syntax.Parser.DotConstructorRejectionTraceProperties
import Solcore.Syntax.DeclarativeParenthesizedTraceOutcomeProperties
import Solcore.Syntax.DeclarativeParenthesizedTraceProtectionProperties
import Solcore.Syntax.DeclarativeParenthesizedRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.ParenthesizedTraceCorrespondenceProperties
import Solcore.Syntax.Parser.ParenthesizedRejectionTraceCorrespondenceProperties
import Solcore.Syntax.DeclarativeProxyExpressionRejectionTraceProperties
import Solcore.Syntax.Parser.ProxyExpressionSuccessTraceProperties
import Solcore.Syntax.Parser.ProxyExpressionRejectionTraceProperties
import Solcore.Syntax.Parser.NamedTypeFinishingTraceProperties
import Solcore.Syntax.DeclarativeOptionalLambdaReturnTypeTraceExactnessProperties
import Solcore.Syntax.DeclarativeOptionalLambdaReturnTypeTraceProtectionProperties
import Solcore.Syntax.Parser.OptionalLambdaReturnTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeQualifiedNameTraceOutcomeProperties
import Solcore.Syntax.Parser.QualifiedNameTraceCorrespondenceProperties
import Solcore.Syntax.Parser.QualifiedNameRejectionTraceStateProperties
import Solcore.Syntax.DeclarativeDelimitedTrailingTraceOutcomeProperties
import Solcore.Syntax.DeclarativeDelimitedTrailingTraceProtectionProperties
import Solcore.Syntax.DeclarativeDelimitedTrailingRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.DelimitedTrailingTraceContextProperties
import Solcore.Syntax.Parser.DelimitedTrailingRejectionTraceCorrespondenceProperties
import Solcore.Syntax.Parser.DelimitedTrailingRejectionTraceTailCorrespondenceProperties
import Solcore.Syntax.DeclarativeNamedTypeArgumentsTraceOutcomeProperties
import Solcore.Syntax.DeclarativeNamedTypeArgumentsRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.NamedTypeArgumentsTraceProperties
import Solcore.Syntax.Parser.NamedTypeArgumentsRejectionTraceProperties
import Solcore.Syntax.DeclarativeNamedTypeTraceOutcomeProperties
import Solcore.Syntax.DeclarativeNamedTypeRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.NamedTypeTraceProperties
import Solcore.Syntax.Parser.NamedTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeMappingTypeTraceOutcomeProperties
import Solcore.Syntax.DeclarativeMappingTypeRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.MappingTypeTraceProperties
import Solcore.Syntax.Parser.MappingTypeRejectionTraceCorrespondenceProperties
import Solcore.Syntax.DeclarativeProxyTypeRejectionTraceProperties
import Solcore.Syntax.Parser.ProxyTypeSuccessTraceProperties
import Solcore.Syntax.Parser.ProxyTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeComptimeTypeRejectionTraceProperties
import Solcore.Syntax.Parser.ComptimeTypeSuccessTraceProperties
import Solcore.Syntax.Parser.ComptimeTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeTupleTypeRejectionTraceProperties
import Solcore.Syntax.Parser.TupleTypeSuccessTraceProperties
import Solcore.Syntax.Parser.TupleTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeFunctionReturnsRejectionTraceProperties
import Solcore.Syntax.Parser.FunctionReturnsTraceProperties
import Solcore.Syntax.Parser.FunctionReturnsRejectionTraceProperties
import Solcore.Syntax.DeclarativeFunctionTypeRejectionTraceProperties
import Solcore.Syntax.Parser.FunctionTypeRejectionTraceProperties
import Solcore.Syntax.Parser.TypeSuccessContextProperties
import Solcore.Syntax.DeclarativeTypeDispatchTraceOrdinaryProperties
import Solcore.Syntax.Parser.TypeDispatchSuccessTraceProperties
import Solcore.Syntax.Parser.TypeDispatchRejectionTraceProperties
import Solcore.Syntax.DeclarativeTypeDispatchTraceMonotonicityProperties
import Solcore.Syntax.Parser.DiagnosticTraceCompletenessFromSoundnessProperties
import Solcore.Syntax.DeclarativeTypeExprTraceStructuralProperties
import Solcore.Syntax.Parser.TypeExprTraceSoundnessProperties

/-! Exact primitive, pragma success/rejection, and recovery traces with independent
mixed-report filtering. Complete public slices cover empty tokens, one top-item
recovery, arbitrary successful pragma sequences, and successful pragma prefixes
ending at recognized rejection. Sequencing, transactional choice, and balanced
isolation have compositional execution laws. Independent isolation traces lift
explicit inner trace contracts. Raw and isolated Core blocks have full trace
correspondence under statement contracts. Concrete break/continue leaves have
unconditional exact traces. Return traces compose explicit expression contracts.
Literal/Boolean primitives and literal/identifier-expression leaves have exact traces;
Raw block statements inherit exact traces under inner statement contracts;
protected earlier events compose through successful and rejected raw statements;
generic no-trailing lists have exact success/rejection traces under child contracts;
array literals inherit five expression contracts and exact AST mapping;
leading-dot constructors preserve Boolean-first name events before argument traces;
parenthesized groups/tuples have conditional exact traces with silent closes and
right-paren-only reports after non-comma successful children;
proxy expressions retain nested type events and exact raw failures under type contracts;
named-type finishing unconditionally records bare-mapping constraint events;
optional lambda return annotations lift real type outcomes and bypass absent arrows;
qualified names unconditionally retain checked components and full success/rejection states;
trailing-enabled lists preserve comma-first and immediate-close priority under child contracts;
optional named-type arguments inherit exact nonempty-list outcomes and silent absence;
raw named types compose name, argument, and finishing events without dispatch assumptions;
raw mapping types retain exact key/value events and all six first-failure positions;
raw proxy types forward nested type outcomes with no extra success/rejection frame premise;
raw comptime types retain the nested event suffix and all four first-failure positions;
raw tuple types retain every element, including empty and singleton lists;
optional function returns preserve silent absence and exact trailing-list outcomes;
raw function types retain exact parameter-before-return events and complete component states;
all recursive type successes unconditionally preserve source and full active window;
one type-dispatch layer preserves all prioritized guards and exact outcomes under child trace contracts;
child-relation implication lifts through lists, raw types, and dispatch without altering any traced data;
both trace soundness laws plus independent exactness and explicit invariant exclusion yield completeness;
recursive type successes and rejections have unconditional fuel-free traces with protected events;
general expressions and remaining statement traces remain open. -/
