import Solcore.Syntax.Parser.PublicSingleRecoveryOutputProperties
import Solcore.Syntax.Parser.UnexpectedDiagnosticCascadeProperties
import Solcore.Syntax.Parser.SourceFileBoundaryStopTraceProperties
import Solcore.Syntax.Parser.PublicPragmaNameRejectionOutputProperties
import Solcore.Syntax.Parser.ParseDiagnosticCascadeProperties
import Solcore.Syntax.Parser.IdentifierTraceProperties
import Solcore.Syntax.Parser.ExactTokenPrimitiveRejectionTraceProperties
import Solcore.Syntax.Parser.SourceFileSingleSuccessTraceProperties
import Solcore.Syntax.DeclarativeIdentifierCascadeProperties
import Solcore.Syntax.Parser.PublicPragmaSuccessOutputProperties
import Solcore.Syntax.Parser.PublicEmptyTokensOutputProperties
import Solcore.Syntax.Parser.TransactionalChoiceDiagnosticTraceProperties
import Solcore.Syntax.Parser.ParseDiagnosticCascadeStabilityProperties
import Solcore.Syntax.Parser.PublicPragmaSequenceOutputProperties
import Solcore.Syntax.Parser.PublicPragmaRejectionOutputProperties
import Solcore.Syntax.DeclarativePragmaRejectionCascadeProperties
import Solcore.Syntax.Parser.PublicPragmaPrefixBoundaryOutputProperties
import Solcore.Syntax.DeclarativeIsolatedBlockTraceProperties
import Solcore.Syntax.Parser.IsolatedBlockTraceCompletenessProperties
import Solcore.Syntax.DeclarativeCoreBlockTailCascadeProperties
import Solcore.Syntax.Parser.CoreBlockClosingTraceProperties
import Solcore.Syntax.DeclarativeCoreBlockTraceExactnessProperties
import Solcore.Syntax.DeclarativeCoreBlockCascadeProperties
import Solcore.Syntax.Parser.CoreBlockIsolationTraceProperties
import Solcore.Syntax.DeclarativeTerminatedControlTraceExactnessProperties
import Solcore.Syntax.Parser.ControlLeafDiagnosticTraceProperties
import Solcore.Syntax.DeclarativeReturnStatementTraceExactnessProperties
import Solcore.Syntax.Parser.ReturnStatementSuccessTraceProperties
import Solcore.Syntax.Parser.ReturnStatementRejectionTraceCompletenessProperties
import Solcore.Syntax.DeclarativeLiteralExpressionTraceExactnessProperties
import Solcore.Syntax.Parser.BooleanIdentifierRejectionTraceProperties
import Solcore.Syntax.Parser.LiteralExpressionTraceProperties
import Solcore.Syntax.Parser.BlockStatementTraceProperties
import Solcore.Syntax.Parser.IdentifierExpressionTraceProperties
import Solcore.Syntax.DeclarativeExpressionNameTraceProtectionProperties
import Solcore.Syntax.DeclarativeRejectionTraceProtectionProperties
import Solcore.Syntax.DeclarativeDelimitedNoTrailingTraceOutcomeProperties
import Solcore.Syntax.DeclarativeDelimitedNoTrailingTraceProtectionProperties
import Solcore.Syntax.Parser.DelimitedNoTrailingTraceContextProperties
import Solcore.Syntax.Parser.DelimitedNoTrailingRejectionTraceCorrespondenceProperties
import Solcore.Syntax.Parser.DelimitedNoTrailingTailRejectionTraceCorrespondenceProperties
import Solcore.Syntax.DeclarativeArrayLiteralTraceProperties
import Solcore.Syntax.Parser.ArrayLiteralTraceProperties
import Solcore.Syntax.DeclarativeDotConstructorTraceOutcomeProperties
import Solcore.Syntax.DeclarativeDotConstructorTraceProtectionProperties
import Solcore.Syntax.DeclarativeDotConstructorRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.DotConstructorSuccessTraceProperties
import Solcore.Syntax.Parser.DotConstructorRejectionTraceProperties
import Solcore.Syntax.DeclarativeParenthesizedTraceOutcomeProperties
import Solcore.Syntax.DeclarativeParenthesizedTraceProtectionProperties
import Solcore.Syntax.DeclarativeParenthesizedRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.ParenthesizedTraceCorrespondenceProperties
import Solcore.Syntax.Parser.ParenthesizedRejectionTraceCorrespondenceProperties
import Solcore.Syntax.DeclarativeProxyExpressionRejectionTraceProperties
import Solcore.Syntax.Parser.ProxyExpressionSuccessTraceProperties
import Solcore.Syntax.Parser.ProxyExpressionRejectionTraceProperties
import Solcore.Syntax.Parser.NamedTypeFinishingTraceProperties
import Solcore.Syntax.DeclarativeOptionalLambdaReturnTypeTraceExactnessProperties
import Solcore.Syntax.DeclarativeOptionalLambdaReturnTypeTraceProtectionProperties
import Solcore.Syntax.Parser.OptionalLambdaReturnTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeQualifiedNameTraceOutcomeProperties
import Solcore.Syntax.Parser.QualifiedNameTraceCorrespondenceProperties
import Solcore.Syntax.Parser.QualifiedNameRejectionTraceStateProperties
import Solcore.Syntax.DeclarativeDelimitedTrailingTraceOutcomeProperties
import Solcore.Syntax.DeclarativeDelimitedTrailingTraceProtectionProperties
import Solcore.Syntax.DeclarativeDelimitedTrailingRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.DelimitedTrailingTraceContextProperties
import Solcore.Syntax.Parser.DelimitedTrailingRejectionTraceCorrespondenceProperties
import Solcore.Syntax.Parser.DelimitedTrailingRejectionTraceTailCorrespondenceProperties
import Solcore.Syntax.DeclarativeNamedTypeArgumentsTraceOutcomeProperties
import Solcore.Syntax.DeclarativeNamedTypeArgumentsRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.NamedTypeArgumentsTraceProperties
import Solcore.Syntax.Parser.NamedTypeArgumentsRejectionTraceProperties
import Solcore.Syntax.DeclarativeNamedTypeTraceOutcomeProperties
import Solcore.Syntax.DeclarativeNamedTypeRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.NamedTypeTraceProperties
import Solcore.Syntax.Parser.NamedTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeMappingTypeTraceOutcomeProperties
import Solcore.Syntax.DeclarativeMappingTypeRejectionTraceProtectionProperties
import Solcore.Syntax.Parser.MappingTypeTraceProperties
import Solcore.Syntax.Parser.MappingTypeRejectionTraceCorrespondenceProperties
import Solcore.Syntax.DeclarativeProxyTypeRejectionTraceProperties
import Solcore.Syntax.Parser.ProxyTypeSuccessTraceProperties
import Solcore.Syntax.Parser.ProxyTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeComptimeTypeRejectionTraceProperties
import Solcore.Syntax.Parser.ComptimeTypeSuccessTraceProperties
import Solcore.Syntax.Parser.ComptimeTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeTupleTypeRejectionTraceProperties
import Solcore.Syntax.Parser.TupleTypeSuccessTraceProperties
import Solcore.Syntax.Parser.TupleTypeRejectionTraceProperties
import Solcore.Syntax.DeclarativeFunctionReturnsRejectionTraceProperties
import Solcore.Syntax.Parser.FunctionReturnsTraceProperties
import Solcore.Syntax.Parser.FunctionReturnsRejectionTraceProperties
import Solcore.Syntax.DeclarativeFunctionTypeRejectionTraceProperties
import Solcore.Syntax.Parser.FunctionTypeRejectionTraceProperties
import Solcore.Syntax.Parser.TypeSuccessContextProperties
import Solcore.Syntax.DeclarativeTypeDispatchTraceOrdinaryProperties
import Solcore.Syntax.Parser.TypeDispatchSuccessTraceProperties
import Solcore.Syntax.Parser.TypeDispatchRejectionTraceProperties
import Solcore.Syntax.DeclarativeTypeDispatchTraceMonotonicityProperties
import Solcore.Syntax.Parser.DiagnosticTraceCompletenessFromSoundnessProperties
import Solcore.Syntax.DeclarativeTypeExprTraceStructuralProperties
import Solcore.Syntax.Parser.TypeExprTraceSoundnessProperties
import Solcore.Syntax.Parser.TypeExprTraceCompletenessProperties
import Solcore.Syntax.Parser.TypeExprTraceUnrestrictedProperties
import Solcore.Syntax.Parser.TypeExprTraceExistenceProperties
import Solcore.Syntax.Parser.ProxyExpressionTypeTraceProperties
import Solcore.Syntax.Parser.OptionalLambdaReturnTypeConcreteTraceProperties
import Solcore.Syntax.Parser.SourceFrameProperties
import Solcore.Syntax.Parser.DelimitedSourceFrameProperties
import Solcore.Syntax.Parser.TypeSourceFrameProperties
import Solcore.Syntax.Parser.DiagnosticTraceStateProperties
import Solcore.Syntax.Parser.TypeExprTraceStateProperties
import Solcore.Syntax.DeclarativeTypedParameterFinishingTraceGrammar
import Solcore.Syntax.DeclarativeTypedParameterFinishingTraceProperties
import Solcore.Syntax.Parser.TypedParameterFinishingTraceProperties
import Solcore.Syntax.DeclarativeNamedParameterTailTraceGrammar
import Solcore.Syntax.DeclarativeNamedParameterTailTraceProperties
import Solcore.Syntax.Parser.NamedParameterTailTraceProperties
import Solcore.Syntax.Parser.NamedParameterTailTraceStateProperties
import Solcore.Syntax.DeclarativeParameterNameFinishingTraceProperties
import Solcore.Syntax.Parser.ParameterNameFinishingTraceProperties
import Solcore.Syntax.Parser.ParameterSourceFrameProperties
import Solcore.Syntax.Parser.ParameterDispatchTraceProperties
import Solcore.Syntax.DeclarativeNamedParameterRawTraceGrammar
import Solcore.Syntax.DeclarativeNamedParameterRawTraceProperties
import Solcore.Syntax.DeclarativeNamedParameterRawRejectionTraceProperties
import Solcore.Syntax.Parser.OrdinaryNamedParameterTraceProperties
import Solcore.Syntax.Parser.ComptimeNamedParameterTraceProperties
import Solcore.Syntax.Parser.NamedParameterRawTraceStateProperties
import Solcore.Syntax.DeclarativeNamedParameterCoreTraceGrammar
import Solcore.Syntax.DeclarativeNamedParameterCoreTraceProperties
import Solcore.Syntax.Parser.NamedParameterCoreTraceProperties
import Solcore.Syntax.Parser.NamedParameterCoreTraceExistenceProperties
import Solcore.Syntax.DeclarativeLambdaParameterTailTraceGrammar
import Solcore.Syntax.DeclarativeLambdaParameterTailTraceProperties
import Solcore.Syntax.Parser.LambdaParameterTailTraceProperties
import Solcore.Syntax.Parser.LambdaParameterTailTraceStateProperties
import Solcore.Syntax.DeclarativeParameterRecoveryTraceGrammar
import Solcore.Syntax.DeclarativeParameterRecoveryTraceProperties
import Solcore.Syntax.Parser.ParameterRecoveryTraceStateProperties
import Solcore.Syntax.Parser.ParameterRecoveryTraceProperties
import Solcore.Syntax.DeclarativeNamedParameterTraceGrammar
import Solcore.Syntax.DeclarativeNamedParameterTraceProperties
import Solcore.Syntax.Parser.NamedParameterTraceProperties
import Solcore.Syntax.Parser.NamedParameterTraceStateProperties
import Solcore.Syntax.DeclarativeLambdaParameterRawTraceGrammar
import Solcore.Syntax.DeclarativeLambdaParameterRawTraceProperties
import Solcore.Syntax.DeclarativeLambdaParameterRawRejectionTraceProperties
import Solcore.Syntax.Parser.OrdinaryLambdaParameterTraceProperties
import Solcore.Syntax.Parser.ComptimeLambdaParameterTraceProperties
import Solcore.Syntax.Parser.LambdaParameterRawTraceStateProperties
import Solcore.Syntax.DeclarativeLambdaParameterCoreTraceGrammar
import Solcore.Syntax.DeclarativeLambdaParameterCoreTraceProperties
import Solcore.Syntax.Parser.LambdaParameterCoreTraceProperties
import Solcore.Syntax.Parser.LambdaParameterCoreTraceExistenceProperties
import Solcore.Syntax.DeclarativeLambdaParameterRecoveryTraceGrammar
import Solcore.Syntax.DeclarativeLambdaParameterRecoveryTraceProperties
import Solcore.Syntax.Parser.LambdaParameterRecoveryTraceProperties
import Solcore.Syntax.DeclarativeLambdaParameterTraceGrammar
import Solcore.Syntax.DeclarativeLambdaParameterTraceProperties
import Solcore.Syntax.Parser.LambdaParameterTraceProperties
import Solcore.Syntax.Parser.LambdaParameterTraceStateProperties
import Solcore.Syntax.DeclarativeParameterListTraceGrammar
import Solcore.Syntax.DeclarativeParameterListTraceProperties
import Solcore.Syntax.Parser.FunctionParametersTraceProperties
import Solcore.Syntax.Parser.LambdaParametersTraceProperties
import Solcore.Syntax.DeclarativeLambdaExpressionTraceGrammar
import Solcore.Syntax.DeclarativeLambdaExpressionTraceProperties
import Solcore.Syntax.Parser.LambdaExpressionSuccessTraceProperties
import Solcore.Syntax.Parser.LambdaExpressionRejectionTraceProperties
import Solcore.Syntax.Parser.LambdaExpressionRejectionTraceStateProperties
import Solcore.Syntax.Parser.LambdaExpressionTraceProperties
import Solcore.Syntax.DeclarativeExpressionAtomDispatchSelectionGrammar
import Solcore.Syntax.DeclarativeExpressionAtomDispatchSelectionProperties
import Solcore.Syntax.Parser.ExpressionAtomDispatchSelectionTraceProperties
import Solcore.Syntax.DeclarativeExpressionAtomRecoveryTraceGrammar
import Solcore.Syntax.DeclarativeExpressionAtomRecoveryTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomRecoveryTraceStateProperties
import Solcore.Syntax.Parser.ExpressionAtomRecoveryTraceProperties
import Solcore.Syntax.DeclarativeExpressionAtomDispatchTraceGrammar
import Solcore.Syntax.DeclarativeExpressionAtomDispatchTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomDispatchSuccessTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomDispatchRejectionTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomDispatchTraceCorrespondenceProperties
import Solcore.Syntax.Parser.ExpressionCollectionRejectionContextProperties
import Solcore.Syntax.Parser.ExpressionAtomDispatchRejectionContextProperties
import Solcore.Syntax.DeclarativeExpressionAtomTraceGrammar
import Solcore.Syntax.DeclarativeExpressionAtomTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomTraceContextProperties
import Solcore.Syntax.Parser.ExpressionAtomTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomTraceStateProperties
import Solcore.Syntax.DeclarativeExpressionAtomLayerTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomLayerTraceProperties
import Solcore.Syntax.Parser.ExpressionAtomLayerTraceExistenceProperties
import Solcore.Syntax.Parser.ExpressionAtomTupleUnrestrictedFuelTotalityProperties
import Solcore.Syntax.Parser.ExpressionAtomCollectionUnrestrictedFuelTotalityProperties
import Solcore.Syntax.Parser.ExpressionAtomUnrestrictedFuelTotalityProperties
import Solcore.Syntax.DeclarativePostfixTailTraceGrammar
import Solcore.Syntax.DeclarativePostfixTailRejectionTraceGrammar
import Solcore.Syntax.DeclarativePostfixTailTraceProperties
import Solcore.Syntax.DeclarativePostfixTailRejectionTraceProperties
import Solcore.Syntax.Parser.PostfixTailSuccessTraceSoundnessProperties
import Solcore.Syntax.Parser.PostfixTailRejectionTraceSoundnessProperties
import Solcore.Syntax.Parser.PostfixTailUnrestrictedFuelTotalityProperties
import Solcore.Syntax.Parser.PostfixTailTraceContextProperties
import Solcore.Syntax.Parser.PostfixTailTraceCompletenessProperties
import Solcore.Syntax.Parser.PostfixTailRejectionTraceCompletenessProperties
import Solcore.Syntax.Parser.PostfixTailTraceCorrespondenceProperties
import Solcore.Syntax.Parser.PostfixTailBoundedTraceProperties
import Solcore.Syntax.Parser.PostfixTailTraceStateProperties
import Solcore.Syntax.DeclarativeExpressionPostfixTraceGrammar
import Solcore.Syntax.DeclarativeExpressionPostfixTraceProperties
import Solcore.Syntax.Parser.ExpressionPostfixTraceSoundnessProperties
import Solcore.Syntax.Parser.ExpressionPostfixTraceContextProperties
import Solcore.Syntax.Parser.ExpressionPostfixUnrestrictedFuelTotalityProperties
import Solcore.Syntax.Parser.ExpressionPostfixTraceExistenceProperties
import Solcore.Syntax.Parser.ExpressionPostfixTraceCorrespondenceProperties
import Solcore.Syntax.Parser.ExpressionPostfixTraceStateProperties
import Solcore.Syntax.Parser.ExpressionAtomBoundedBodyFuelTotalityProperties
import Solcore.Syntax.DeclarativeExpressionPostfixLayerTraceProperties
import Solcore.Syntax.Parser.ExpressionPostfixLayerTraceProperties
import Solcore.Syntax.Parser.DelimitedNumericWindowProperties
import Solcore.Syntax.Parser.ExpressionCollectionNumericWindowProperties
import Solcore.Syntax.Parser.ExpressionAtomNumericWindowProperties
import Solcore.Syntax.Parser.ExpressionAtomUnrestrictedChildContractProperties
import Solcore.Syntax.Parser.PostfixNumericWindowProperties
import Solcore.Syntax.Parser.ExpressionPostfixUnrestrictedChildContractProperties
import Solcore.Syntax.Parser.ExpressionPostfixLayerTraceExistenceProperties
import Solcore.Syntax.DeclarativeExpressionUnaryTraceGrammar
import Solcore.Syntax.DeclarativeExpressionUnaryTraceProperties
import Solcore.Syntax.Parser.UnaryOperatorsTraceProperties
import Solcore.Syntax.Parser.ExpressionUnaryTraceProperties
import Solcore.Syntax.Parser.ExpressionUnaryTraceCorrespondenceProperties
import Solcore.Syntax.Parser.ExpressionUnaryTraceStateProperties

/-! Exact primitive, pragma success/rejection, and recovery traces with independent
mixed-report filtering. Complete public slices cover empty tokens, one top-item
recovery, arbitrary successful pragma sequences, and successful pragma prefixes
ending at recognized rejection. Sequencing, transactional choice, and balanced
isolation have compositional execution laws. Independent isolation traces lift
explicit inner trace contracts. Raw and isolated Core blocks have full trace
correspondence under statement contracts. Concrete break/continue leaves have
unconditional exact traces. Return traces compose explicit expression contracts.
Literal/Boolean primitives and literal/identifier-expression leaves have exact traces;
Raw block statements inherit exact traces under inner statement contracts;
protected earlier events compose through successful and rejected raw statements;
generic no-trailing lists have exact success/rejection traces under child contracts;
array literals inherit five expression contracts and exact AST mapping;
leading-dot constructors preserve Boolean-first name events before argument traces;
parenthesized groups/tuples have conditional exact traces with silent closes and
right-paren-only reports after non-comma successful children;
proxy expressions retain nested type events and exact raw failures under type contracts;
named-type finishing unconditionally records bare-mapping constraint events;
optional lambda return annotations lift real type outcomes and bypass absent arrows;
qualified names unconditionally retain checked components and full success/rejection states;
trailing-enabled lists preserve comma-first and immediate-close priority under child contracts;
optional named-type arguments inherit exact nonempty-list outcomes and silent absence;
raw named types compose name, argument, and finishing events without dispatch assumptions;
raw mapping types retain exact key/value events and all six first-failure positions;
raw proxy types forward nested type outcomes with no extra success/rejection frame premise;
raw comptime types retain the nested event suffix and all four first-failure positions;
raw tuple types retain every element, including empty and singleton lists;
optional function returns preserve silent absence and exact trailing-list outcomes;
raw function types retain exact parameter-before-return events and complete component states;
all recursive type successes unconditionally preserve source and full active window;
one type-dispatch layer preserves all prioritized guards and exact outcomes under child trace contracts;
child-relation implication lifts through lists, raw types, and dispatch without altering any traced data;
both trace soundness laws plus independent exactness and explicit invariant exclusion yield completeness;
recursive type successes and rejections have unconditional fuel-free traces with protected events;
independent recursive type outcomes are unique and disjoint, with unconditional production trace completeness;
separate totality and soundness supply an actual traced outcome on every state and independent remainder;
recursive type traces reconstruct every field of successful and rejected states;
proxy expressions and optional lambda returns instantiate concrete unrestricted type contracts;
typed and error parameter finishers retain exact values and append only their own constraint events;
named parameter tails have unconditional five contracts, whole-State equivalences, and ordered type/finishing events;
ordinary name checks preserve exact prefix events, while both parameter dispatchers select the same window-visible pair;
raw named parameters and their selected non-recovering core have unconditional exact traces and whole-State correspondence;
separate core totality and soundness give non-vacuous traced outcome existence on arbitrary inputs;
lambda parameter tails retag exact typed outcomes and distinguish inferred absence from comptime errors;
standalone parameter recovery has exact full-State traces with conditional recovery-event filtering;
public named parameters compose cursor-only rewind, one report commitment, and exact recovery outcomes;
raw lambda parameters and their pair-selected core preserve exact inferred/typed/error outcomes and complete traces;
standalone lambda recovery preserves function-recovery states and events while retagging only the error AST;
public lambda parameters have exact rewind/recovery traces, whole-State equivalences, and separate outcome existence;
actual function and inline lambda parameter lists inherit unconditional exact traces and separate outcome existence;
raw lambda expressions compose concrete parameters and returns with explicit body trace contracts and conditional filters;
expression-atom guards independently select one of eight raw branches on arbitrary token remainders;
standalone atom recovery preserves exact error ASTs and singleton events, with conditional lexical filtering;
one selected atom-core layer has exact raw trace correspondence under explicit nested-expression and body contracts;
separate rejection frames preserve a chosen window observation, including end-byte-only frames that allow end-index changes;
public atoms compose abstract core traces with exact cursor-only rewind and recovery under explicit source/end-byte frames;
the concrete selected-core/public layer composes recursive child contracts, with separate bounded totality and trace existence;
maximal postfix tails have independent exact prioritized traces and all-fuel ordinary-outcome soundness under child contracts;
postfix derivations execute above their own thresholds, while explicit progress/budgets separately give production totality and trace existence;
pointwise postfix correspondences reconstruct complete States with explicit rejected source/end-byte frames;
actual atom-plus-postfix composition preserves ordered traces and pointwise complete States under explicit atom/nested contracts;
separate bounded composition totality and trace existence still require an atom endpoint budget or a supplied atom contract;
atom ordinary execution also accepts bounded body contracts, and one concrete atom/postfix layer retains explicit child frames;
numeric-only success/rejection frames compose through recovery, constructing an atom fuel contract from two bounded children;
actual postfix contracts now construct the intermediate atom internally, and child-only bounded soundness supplies layer trace existence;
unary prefixes have unconditional silent full-State scanning and existence; corresponding postfix contracts lift independently through unary traces;
general expressions and remaining statement traces remain open. -/
