import Solcore.Syntax.Parser.PublicSingleRecoveryOutputProperties
import Solcore.Syntax.Parser.UnexpectedDiagnosticCascadeProperties
import Solcore.Syntax.Parser.SourceFileBoundaryStopTraceProperties
import Solcore.Syntax.Parser.PublicPragmaNameRejectionOutputProperties
import Solcore.Syntax.Parser.ParseDiagnosticCascadeProperties
import Solcore.Syntax.Parser.IdentifierTraceProperties
import Solcore.Syntax.Parser.ExactTokenPrimitiveRejectionTraceProperties
import Solcore.Syntax.Parser.SourceFileSingleSuccessTraceProperties
import Solcore.Syntax.DeclarativeIdentifierCascadeProperties
import Solcore.Syntax.Parser.PublicPragmaSuccessOutputProperties
import Solcore.Syntax.Parser.PublicEmptyTokensOutputProperties
import Solcore.Syntax.Parser.TransactionalChoiceDiagnosticTraceProperties
import Solcore.Syntax.Parser.ParseDiagnosticCascadeStabilityProperties
import Solcore.Syntax.Parser.PublicPragmaSequenceOutputProperties
import Solcore.Syntax.Parser.PublicPragmaRejectionOutputProperties
import Solcore.Syntax.DeclarativePragmaRejectionCascadeProperties
import Solcore.Syntax.Parser.PublicPragmaPrefixBoundaryOutputProperties
import Solcore.Syntax.DeclarativeIsolatedBlockTraceProperties
import Solcore.Syntax.Parser.IsolatedBlockTraceCompletenessProperties
import Solcore.Syntax.DeclarativeCoreBlockTailCascadeProperties
import Solcore.Syntax.Parser.CoreBlockClosingTraceProperties
import Solcore.Syntax.DeclarativeCoreBlockTraceExactnessProperties
import Solcore.Syntax.DeclarativeCoreBlockCascadeProperties
import Solcore.Syntax.Parser.CoreBlockIsolationTraceProperties
import Solcore.Syntax.DeclarativeTerminatedControlTraceExactnessProperties
import Solcore.Syntax.Parser.ControlLeafDiagnosticTraceProperties
import Solcore.Syntax.DeclarativeReturnStatementTraceExactnessProperties
import Solcore.Syntax.Parser.ReturnStatementSuccessTraceProperties
import Solcore.Syntax.Parser.ReturnStatementRejectionTraceCompletenessProperties
import Solcore.Syntax.DeclarativeLiteralExpressionTraceExactnessProperties
import Solcore.Syntax.Parser.BooleanIdentifierRejectionTraceProperties
import Solcore.Syntax.Parser.LiteralExpressionTraceProperties
import Solcore.Syntax.Parser.BlockStatementTraceProperties
import Solcore.Syntax.Parser.IdentifierExpressionTraceProperties

/-! Exact primitive, pragma success/rejection, and recovery traces with independent
mixed-report filtering. Complete public slices cover empty tokens, one top-item
recovery, arbitrary successful pragma sequences, and successful pragma prefixes
ending at recognized rejection. Sequencing, transactional choice, and balanced
isolation have compositional execution laws. Independent isolation traces lift
explicit inner trace contracts. Raw and isolated Core blocks have full trace
correspondence under statement contracts. Concrete break/continue leaves have
unconditional exact traces. Return traces compose explicit expression contracts.
Literal/Boolean primitives and literal/identifier-expression leaves have exact traces;
Raw block statements inherit exact traces under inner statement contracts;
general expressions and remaining statement traces remain open. -/
