import Solcore.SourceSemantics.Control

/-!
Pure control-summary facts used by source-level preservation.

`BodyFacts` is an intentionally open carrier, so a sequential body's
completion alone does not imply completion of its tail: an arbitrary tail may
have no possible control outcome at all.  Typing-generated bodies exclude that
case.  `ControlSummary.HasOutcome` records exactly the small realizability fact
needed to transport completion to a reachable tail.
-/

set_option autoImplicit false

namespace Solcore.SourceSemantics

namespace ControlSummary

/-- At least one ordinary or non-local control outcome is represented by the
summary.  Every summary generated by source typing has this property. -/
def HasOutcome (summary : ControlSummary) : Prop :=
  summary.canFallthrough = true ∨
    summary.mayReturn = true ∨
    summary.mayBreak = true ∨
    summary.mayContinue = true

@[simp] theorem hasOutcome_ordinary (type : TypeSystem.Ty) :
    (ordinary type).HasOutcome := by
  exact Or.inl rfl

@[simp] theorem hasOutcome_returned : returned.HasOutcome := by
  exact Or.inr (Or.inl rfl)

@[simp] theorem hasOutcome_breaking : breaking.HasOutcome := by
  exact Or.inr (Or.inr (Or.inl rfl))

@[simp] theorem hasOutcome_continuing : continuing.HasOutcome := by
  exact Or.inr (Or.inr (Or.inr rfl))

theorem HasOutcome.sequence {head tail : ControlSummary}
    (head_outcome : head.HasOutcome) (tail_outcome : tail.HasOutcome) :
    (head.sequence tail).HasOutcome := by
  rcases head_outcome with head_falls | head_returns | head_breaks |
    head_continues
  · rcases tail_outcome with tail_falls | tail_returns | tail_breaks |
      tail_continues
    · have head_some : head.fallthrough.isSome = true := by
        simpa [ControlSummary.canFallthrough] using head_falls
      exact Or.inl (by
        simpa [ControlSummary.sequence, ControlSummary.canFallthrough,
          head_some] using tail_falls)
    · exact Or.inr (Or.inl (by
        simp [ControlSummary.sequence, head_falls, tail_returns]))
    · exact Or.inr (Or.inr (Or.inl (by
        simp [ControlSummary.sequence, head_falls, tail_breaks])))
    · exact Or.inr (Or.inr (Or.inr (by
        simp [ControlSummary.sequence, head_falls, tail_continues])))
  · exact Or.inr (Or.inl (by simp [ControlSummary.sequence, head_returns]))
  · exact Or.inr (Or.inr (Or.inl (by
      simp [ControlSummary.sequence, head_breaks])))
  · exact Or.inr (Or.inr (Or.inr (by
      simp [ControlSummary.sequence, head_continues])))

theorem HasOutcome.branches_left {left right : ControlSummary}
    (outcome : left.HasOutcome) : (left.branches right).HasOutcome := by
  rcases outcome with falls | returns | breaks | continues
  · have left_some : left.fallthrough.isSome = true := by
      simpa [ControlSummary.canFallthrough] using falls
    exact Or.inl (by
      simp [branches, ControlSummary.canFallthrough, left_some])
  · exact Or.inr (Or.inl (by simp [branches, returns]))
  · exact Or.inr (Or.inr (Or.inl (by simp [branches, breaks])))
  · exact Or.inr (Or.inr (Or.inr (by simp [branches, continues])))

theorem HasOutcome.branches_right {left right : ControlSummary}
    (outcome : right.HasOutcome) : (left.branches right).HasOutcome := by
  rw [show left.branches right = right.branches left by
    cases left <;> cases right <;>
      simp [branches, Bool.or_comm]]
  exact outcome.branches_left

theorem HasOutcome.eraseValue {summary : ControlSummary}
    (outcome : summary.HasOutcome) : summary.eraseValue.HasOutcome := by
  rcases outcome with falls | returns | breaks | continues
  · exact Or.inl (by
      cases summary with
      | mk fallthrough mayReturn mayBreak mayContinue =>
          cases fallthrough <;>
            simp_all [canFallthrough, ControlSummary.eraseValue])
  · exact Or.inr (Or.inl (by
      simpa [ControlSummary.eraseValue] using returns))
  · exact Or.inr (Or.inr (Or.inl (by
      simpa [ControlSummary.eraseValue] using breaks)))
  · exact Or.inr (Or.inr (Or.inr (by
      simpa [ControlSummary.eraseValue] using continues)))

@[simp] theorem hasOutcome_loop (summary : ControlSummary) :
    summary.loop.HasOutcome := by
  exact Or.inl rfl

end ControlSummary

namespace BodyFacts

@[simp] theorem empty_hasOutcome : empty.control.HasOutcome := by
  exact ControlSummary.hasOutcome_ordinary .unit

theorem singleton_hasOutcome {statement : StatementFacts}
    (outcome : statement.control.HasOutcome) :
    (singleton statement).control.HasOutcome := by
  exact outcome

theorem cons_hasOutcome {head : StatementFacts} {tail : BodyFacts}
    (head_outcome : head.control.HasOutcome)
    (tail_outcome : tail.control.HasOutcome) :
    (cons head tail).control.HasOutcome := by
  exact head_outcome.sequence tail_outcome

end BodyFacts

namespace BodyCompletes

/-- Completion passes to a reachable tail once the tail is known to denote at
least one possible control outcome.  The latter premise is essential because
`BodyFacts` itself is an open carrier rather than a typing derivation. -/
theorem tail_of_cons_of_hasOutcome {expected : TypeSystem.Ty}
    {head : StatementFacts} {tail : BodyFacts}
    (head_falls : head.control.canFallthrough = true)
    (tail_outcome : tail.control.HasOutcome)
    (complete : BodyCompletes expected (.cons head tail)) :
    BodyCompletes expected tail := by
  rcases complete with ⟨no_break, no_continue, completion⟩
  simp only [BodyFacts.cons, ControlSummary.sequence, head_falls, if_true] at no_break no_continue completion
  have tail_no_break : tail.control.mayBreak = false := by
    exact Bool.or_eq_false_iff.mp no_break |>.2
  have tail_no_continue : tail.control.mayContinue = false := by
    exact Bool.or_eq_false_iff.mp no_continue |>.2
  refine ⟨tail_no_break, tail_no_continue, ?_⟩
  rcases completion with completion | completion
  · rcases completion with ⟨tail_fallthrough, sequence_returns⟩
    left
    refine ⟨tail_fallthrough, ?_⟩
    rcases tail_outcome with
      tail_falls | tail_returns | tail_breaks | tail_continues
    · simp [ControlSummary.canFallthrough, tail_fallthrough] at tail_falls
    · exact tail_returns
    · rw [tail_no_break] at tail_breaks
      contradiction
    · rw [tail_no_continue] at tail_continues
      contradiction
  · exact Or.inr completion

end BodyCompletes

end Solcore.SourceSemantics
