import Solcore.SourceSemantics.CoreLowering.StagedValue
import Solcore.SourceSemantics.CoreLowering.Literals
import Solcore.SourceSemantics.CoreLowering.LocalCell
import Solcore.SourceSemantics.CoreLowering.HeapMutation
import Solcore.SourceSemantics.CoreLowering.BasicExpressions
import Solcore.SourceSemantics.CoreLowering.BasicStatements
import Solcore.SourceSemantics.CoreLowering.BasicExpressionCertificates
import Solcore.SourceSemantics.CoreLowering.BasicStatementCertificates
import Solcore.SourceSemantics.CoreLowering.BasicStatementMeaning
import Solcore.SourceSemantics.CoreLowering.ControlExpressions
import Solcore.SourceSemantics.CoreLowering.PrimitiveExpressions
import Solcore.SourceSemantics.CoreLowering.GeneralHeap
import Solcore.SourceSemantics.CoreLowering.GeneralExpressions
import Solcore.SourceSemantics.CoreLowering.GeneralStatements

import Solcore.SourceSemantics.CoreLowering.BasicStatementTreeCertificates
import Solcore.SourceSemantics.CoreLowering.WordMapping

import Solcore.SourceSemantics.CoreLowering.IntegerPrimitives
import Solcore.SourceSemantics.CoreLowering.ControlStatementBridge

import Solcore.SourceSemantics.CoreLowering.OrderedMapping
import Solcore.SourceSemantics.CoreLowering.DataEquality
import Solcore.SourceSemantics.CoreLowering.DataDefaults
import Solcore.SourceSemantics.CoreLowering.ScalarExpressionReflection
import Solcore.SourceSemantics.CoreLowering.LoopStatementBridge
import Solcore.SourceSemantics.CoreLowering.LoopStatementReflectionBridge
import Solcore.SourceSemantics.CoreLowering.DataPatternDecision
import Solcore.SourceSemantics.CoreLowering.DataPatternEncoding
import Solcore.SourceSemantics.CoreLowering.DataPatternParametricLeaves
import Solcore.SourceSemantics.CoreLowering.DataPlaceMembers
import Solcore.SourceSemantics.CoreLowering.DataPlaceCertificates
import Solcore.SourceSemantics.CoreLowering.DataPlaceMemberCertificates
import Solcore.SourceSemantics.CoreLowering.ForLoopStatementCertificates
import Solcore.SourceSemantics.CoreLowering.ForPostMeaning
import Solcore.SourceSemantics.CoreLowering.ForStatementCorrespondence

/-! Proofs connecting executable Core lowering to the independent source
semantics. This boundary is separate from the specification's umbrella so that
the specification does not depend on executable frontend passes. -/
