import Solcore.SourceSemantics.CoreLowering.ProtectedStateMatchBodyContracts

/-! Finite forward correspondence for the actual compatible match head.
Independent source allocation determines the selected lexical environment;
the emitted marked prefix supplies the actual typed captures and frame.
Arm and default contracts are structural induction interfaces. -/
set_option autoImplicit false
namespace Solcore.SourceSemantics.CoreLowering.CompatibleMatchPreservation
open Core Frontend SourceInference GeneralHeap ReadOnly CompatiblePayload CoreProof
open SourceCoreCompatibleDataMatches CompatibleMatchCertificates CompatibleMatchMeaning
open DataMatchBranchPrefix GenericLexicalContext CallableIndexedHistory
open TypedLexicalWhile (FlowRep Restored restored restore_rep)
universe u v

private theorem read_contains {checked : SourceCoreCompatibleCatalog.Checked} {source : TypedSource}
    {id : StatementId} {node : StatementNode} {type : Ty}
    (read : SourceCoreCompatibleDataExpressions.readStatement checked source id = .ok (node, type)) :
    ContainsStatement source id node := by
  by_cases owned : id.occurrence.owner = source.owner
  · simp only [SourceCoreCompatibleDataExpressions.readStatement, owned, ne_eq, not_true_eq_false, ↓reduceIte,
      pure, Except.pure, bind, Except.bind] at read
    cases found : source.lookupStatement? id with
    | none => simp [found] at read
    | some selected =>
      simp only [found] at read
      cases projected : SourceCoreCompatibleDataExpressions.projectType checked (.occurrence id.occurrence) selected.type with
      | error => simp [projected] at read
      | ok projectedType =>
        simp only [projected, Except.ok.injEq, Prod.mk.injEq] at read
        rcases read with ⟨rfl, rfl⟩
        exact lookupStatement?_sound found
  · simp [SourceCoreCompatibleDataExpressions.readStatement, owned, bind, Except.bind] at read

private theorem default_selected {context : SourceSemantics.Context} {value : Dynamic.Value}
    {cases : List TypedMatchCase} {fallback : Option (List StatementId)} {statements : List StatementId}
    (selected : Dynamic.MatchCasesSelect context value cases fallback (.default statements)) :
    fallback = some statements := by
  cases selected with
  | default => rfl
  | tail _ next => exact default_selected next
termination_by cases.length
decreasing_by simp_all

private theorem allocations_same {before left right : Dynamic.Heap} {type : TypeSystem.Ty} {value : Option Dynamic.Value}
    {a b : Dynamic.Location} (first : Dynamic.Heap.Allocates before type value a left)
    (second : Dynamic.Heap.Allocates before type value b right) : left = right := by
  cases first; cases second; rfl

private theorem binders_same {environment a b : Dynamic.Environment} {before left right : Dynamic.Heap}
    {binders : List TypedBinder} {values : List Dynamic.Value}
    (first : Dynamic.BindersAllocate environment before binders values a left)
    (second : Dynamic.BindersAllocate environment before binders values b right) : a = b ∧ left = right := by
  induction first generalizing b right with
  | nil => cases second; exact ⟨rfl, rfl⟩
  | cons allocation rest ih =>
    cases second with
    | cons allocation' rest' =>
      cases allocation
      cases allocation'
      exact ih rest'

private theorem extensions_same {owner : Resolved.DeclarationId} {context a b : SourceSemantics.Context}
    {binders : List TypedBinder} (first : BindersExtend owner context binders a)
    (second : BindersExtend owner context binders b) : a = b := by
  induction first generalizing b with
  | nil => cases second; rfl
  | cons head tail ih =>
    cases second with
    | cons head' tail' =>
      cases head
      cases head'
      exact ih tail'

/-- The supplied source trace selects the emitted branch. Allocation and binder
 determinism identify its source cells with those generated by the actual prefix. -/
theorem Stateful.Certificate.preserves_trace_bounded_for
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (validity : SourceSemantics.Context → Prop)
    (literals : IntegerLiteralResolution → Prop)
    (signatures : context.signatures = compilation.signatures)
    (numericRequirements : ∀ numeric, literals numeric → RequirementProves context numeric.requirement numeric.predicate)
    (sites : CompatibleMatchDecision.Certificate.LiteralSites literals certificate)
    (validity_binders : ∀ {binders target}, BindersExtend source.owner context binders target →
      validity context → validity target)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (budget : Nat) {Records : Type v}
    (protocol : ProtectedStateTransition.Protocol.{u, v} Records)
    (guard : Location → NativeFrame → Prop)
    (producer : ProtectedStateTransition.MarkedAllocation.Producer protocol layouts frame
      (CompatibleAmbientHeap.payloadModel compilation.checked registry functions))
    (stateBindings : ProtectedStateTransition.Bindings protocol)
    (acquire : ∀ location native, guard location native →
      ProtectedStateTransition.OrdinaryAllocation.ReadyAt producer.toOrdinary location native)
    (expressionMeaning : validity context →
      ∀ child, child < budget → ProtectedStateTransition.PreservesAt protocol (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults child)
    (armMeaning : RecursiveNamedMatchSourceBounds.Stateful.ArmPreservesBelowFor protocol guard functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : RecursiveNamedMatchSourceBounds.Stateful.DefaultPreservesBelowFor protocol guard functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (contextValid : validity context)
    {mapping : LocationMap} {world : StoreTyping} {actualContext : Core.Context}
    {environment : Dynamic.Environment} {canonical actual : Environment} {before after : Dynamic.Heap}
    {store : Store} {ξ : Renaming} {contextLocation : Location} {native : NativeFrame}
    {outcome : Dynamic.ControlOutcome}
    (environments : DataHeap.EnvRepresents (CompatibleEquality.storageCatalog compilation.checked.catalog)
      mapping world administrative scope environment canonical ambient.definitions)
    (heaps : CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions mapping world before store)
    (locals : Dynamic.EnvironmentAgrees before context.locals environment)
    (agrees : EnvironmentsAgree ξ canonical actual)
    (actualTyped : RuntimeEnvironmentHasTypes world actual actualContext ambient.definitions)
    (reference : canonical[scope.length + 1 + globals]? = some (.cellRef frame.type contextLocation))
    (read : store.read? contextLocation = some (SourceCoreCallableIndexedFrames.encode frame native))
    (unmapped : contextLocation ∉ mapping)
    (initial : protocol.State ⟨scope, mapping, world, before, store, canonical⟩)
    (gate : guard contextLocation native)
    (trace : RecursiveNamedMatchSourceBounds.TraceBelow budget program context evidence source environment before resolution outcome after) :
    ∃ value finalStore finalMap finalWorld,
      Evaluates actual store (code.rename ξ) value finalStore ∧
      FlowRep (registry := registry) functions finalMap finalWorld faults expected type outcome value ∧
      CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions finalMap finalWorld after finalStore ∧
      LocationMap.Extends mapping finalMap ∧ WorldExtends world finalWorld ∧
      AdministrativePreserved mapping store finalMap finalStore ∧ Dynamic.HeapMetadataExtend before after ∧
      ProtectedStateTransition.Transition protocol initial ⟨scope, finalMap, finalWorld, after, finalStore, canonical⟩ := by
  have expression : expressionCertificate scope resolution.scrutinee lowered := by
    cases certificate with
    | matchWith _ _ _ _ _ _ _ _ _ certified =>
      exact (uniqueExpression _ certified) ▸ certified
  cases trace with
  | scrutineeFault fault smaller =>
    obtain ⟨value, finalStore, finalMap, finalWorld, coreEval, related, heapRep, maps, worlds, preserved, metadata, post⟩ :=
      expressionMeaning contextValid _ smaller expression found environments heaps locals agrees actualTyped initial (.fault fault)
    cases related with
    | fault represented =>
      exact ⟨_, finalStore, finalMap, finalWorld,
        CompatibleMatchScrutineeReflection.Certificate.failure_preserves certificate uniqueExpression coreEval,
        .fault represented, heapRep, maps, worlds, preserved, metadata, post⟩
  | patternFault contains evaluated _ allocated fault =>
    exact False.elim (CompatibleMatchSourceSelection.Certificate.not_pattern_fault_with_signatures certificate signatures _ fault)
  | @arm sourceNode sourceValue middle hidden location statements bindings armContext armEnvironment bound
      innerFinal innerOutcome sourceAfter exprSize bodySize contains sourceEval exprSmaller sourceHidden selected sourceExtended sourceAllocated sourceBody bodySmaller =>
    have nodeEq : sourceNode = node := Option.some.inj
      ((lookupExpression?_complete unique contains).symm.trans found)
    subst sourceNode
    obtain ⟨value, middleStore, middleMap, middleWorld, coreEval, represented, middleRelated,
      firstMaps, firstWorlds, firstFrame, firstMetadata, firstPost⟩ :=
      expressionMeaning contextValid _ exprSmaller expression found environments heaps locals agrees actualTyped initial (.value sourceEval)
    obtain ⟨middleState, firstRelated⟩ := firstPost
    cases represented with
    | value represented =>
      obtain ⟨stillUnmapped, stillRead⟩ := firstFrame contextLocation unmapped (List.getElem?_eq_some_iff.mp read).1
      obtain ⟨hiddenHeap, hiddenLocation, finalScope, selectedEnvironment, selectedHeap, selectedCanonical,
        selectedActual, selectedStore, selectedMap, selectedWorld, selectedEmbedding, selectedContext, body,
        hiddenAllocated, selectedAgain, selectedBody, selectedEnv, selectedRelated, secondMaps, secondWorlds,
        secondFrame, selectedLayout, selectedTyped, selectedReference, selectedRead, selectedUnmapped, spine, agreement, selectedState, selectionRelated, ⟨returnTo⟩⟩ :=
        CompatibleMatchTypedSelectionPrefix.Stateful.Certificate.selected_prefix_sized_with_literals certificate ordinary onError allocator literals signatures numericRequirements sites
          catalogValid protocol producer stateBindings definitions registered extended found uniqueExpression represented (environments.extend firstMaps firstWorlds)
          middleRelated agrees (actualTyped.weaken firstWorlds) reference (stillRead.trans read) stillUnmapped coreEval middleState (acquire contextLocation native gate) selected
      have hiddenEq := allocations_same hiddenAllocated sourceHidden
      subst hiddenHeap
      cases selectedBody with
      | arm binders allocated bodyCertified =>
        obtain ⟨sameEnvironment, sameHeap⟩ := binders_same allocated sourceAllocated
        subst selectedEnvironment
        subst selectedHeap
        obtain ⟨staticContext, staticFinal, facts, extended, typed, _⟩ :=
          DataMatchSourceScopes.MatchCasesSelect.arm_scope casesTyped selected
        have sameContext := extensions_same extended sourceExtended
        subst staticContext
        obtain ⟨result, finalStore, finalMap, finalWorld, bodyEval, related, finalHeapRep,
          thirdMaps, thirdWorlds, thirdFrame, thirdMetadata, lexical, bodyPost⟩ :=
          armMeaning rfl selected (.arm binders allocated bodyCertified) sourceExtended typed bodySize bodySmaller
            (validity_binders sourceExtended contextValid) selectedEnv selectedRelated
            (binders_agree sourceExtended (arm_monomorphic casesTyped selected)
              (locals.mono (firstMetadata.trans (.of_allocation sourceHidden))) sourceAllocated)
            selectedLayout selectedTyped selectedReference selectedRead selectedUnmapped selectedState gate sourceBody
        obtain ⟨bodyState, bodyRelated⟩ := bodyPost
        exact ⟨result, finalStore, finalMap, finalWorld, agreement.wrap bodyEval, restore_rep related environment,
          finalHeapRep, firstMaps.trans (secondMaps.trans thirdMaps), firstWorlds.trans (secondWorlds.trans thirdWorlds),
          firstFrame.trans (secondFrame.trans thirdFrame),
          firstMetadata.trans ((Dynamic.HeapMetadataExtend.of_allocation sourceHidden).trans
            ((binders_metadata sourceAllocated).trans thirdMetadata)),
          ⟨returnTo.restore bodyState, protocol.trans firstRelated
            (protocol.trans selectionRelated (protocol.trans bodyRelated (returnTo.related bodyState)))⟩⟩
  | @default sourceNode sourceValue middle hidden location statements innerFinal innerOutcome sourceAfter
      exprSize bodySize contains sourceEval exprSmaller sourceHidden selected sourceBody bodySmaller =>
    have nodeEq : sourceNode = node := Option.some.inj
      ((lookupExpression?_complete unique contains).symm.trans found)
    subst sourceNode
    obtain ⟨value, middleStore, middleMap, middleWorld, coreEval, represented, middleRelated,
      firstMaps, firstWorlds, firstFrame, firstMetadata, firstPost⟩ :=
      expressionMeaning contextValid _ exprSmaller expression found environments heaps locals agrees actualTyped initial (.value sourceEval)
    obtain ⟨middleState, firstRelated⟩ := firstPost
    cases represented with
    | value represented =>
      obtain ⟨stillUnmapped, stillRead⟩ := firstFrame contextLocation unmapped (List.getElem?_eq_some_iff.mp read).1
      obtain ⟨hiddenHeap, hiddenLocation, finalScope, selectedEnvironment, selectedHeap, selectedCanonical,
        selectedActual, selectedStore, selectedMap, selectedWorld, selectedEmbedding, selectedContext, body,
        hiddenAllocated, selectedAgain, selectedBody, selectedEnv, selectedRelated, secondMaps, secondWorlds,
        secondFrame, selectedLayout, selectedTyped, selectedReference, selectedRead, selectedUnmapped, spine, agreement, selectedState, selectionRelated, ⟨returnTo⟩⟩ :=
        CompatibleMatchTypedSelectionPrefix.Stateful.Certificate.selected_prefix_sized_with_literals certificate ordinary onError allocator literals signatures numericRequirements sites
          catalogValid protocol producer stateBindings definitions registered extended found uniqueExpression represented (environments.extend firstMaps firstWorlds)
          middleRelated agrees (actualTyped.weaken firstWorlds) reference (stillRead.trans read) stillUnmapped coreEval middleState (acquire contextLocation native gate) selected
      have hiddenEq := allocations_same hiddenAllocated sourceHidden
      subst hiddenHeap
      cases selectedBody with
      | default bodyCertified =>
        obtain ⟨staticFinal, facts, typed⟩ := defaultTyped (default_selected selected)
        obtain ⟨result, finalStore, finalMap, finalWorld, bodyEval, related, finalHeapRep,
          thirdMaps, thirdWorlds, thirdFrame, thirdMetadata, lexical, bodyPost⟩ :=
          defaultMeaning (environment := environment) (heap := hidden) rfl selected (.default bodyCertified) typed bodySize bodySmaller
            contextValid selectedEnv selectedRelated
            (locals.mono (firstMetadata.trans (.of_allocation sourceHidden))) selectedLayout selectedTyped selectedReference selectedRead selectedUnmapped selectedState gate sourceBody
        obtain ⟨bodyState, bodyRelated⟩ := bodyPost
        exact ⟨result, finalStore, finalMap, finalWorld, agreement.wrap bodyEval, restore_rep related environment,
          finalHeapRep, firstMaps.trans (secondMaps.trans thirdMaps), firstWorlds.trans (secondWorlds.trans thirdWorlds),
          firstFrame.trans (secondFrame.trans thirdFrame),
          firstMetadata.trans ((Dynamic.HeapMetadataExtend.of_allocation sourceHidden).trans thirdMetadata),
          ⟨returnTo.restore bodyState, protocol.trans firstRelated
            (protocol.trans selectionRelated (protocol.trans bodyRelated (returnTo.related bodyState)))⟩⟩
  | @noBranch sourceNode sourceValue middle hidden location exprSize contains sourceEval exprSmaller sourceHidden selected =>
    have nodeEq : sourceNode = node := Option.some.inj
      ((lookupExpression?_complete unique contains).symm.trans found)
    subst sourceNode
    obtain ⟨value, middleStore, middleMap, middleWorld, coreEval, represented, middleRelated,
      firstMaps, firstWorlds, firstFrame, firstMetadata, firstPost⟩ :=
      expressionMeaning contextValid _ exprSmaller expression found environments heaps locals agrees actualTyped initial (.value sourceEval)
    obtain ⟨middleState, firstRelated⟩ := firstPost
    cases represented with
    | value represented =>
      obtain ⟨stillUnmapped, stillRead⟩ := firstFrame contextLocation unmapped (List.getElem?_eq_some_iff.mp read).1
      obtain ⟨hiddenHeap, hiddenLocation, finalScope, selectedEnvironment, selectedHeap, selectedCanonical,
        selectedActual, selectedStore, selectedMap, selectedWorld, selectedEmbedding, selectedContext, body,
        hiddenAllocated, selectedAgain, selectedBody, selectedEnv, selectedRelated, secondMaps, secondWorlds,
        secondFrame, selectedLayout, selectedTyped, selectedReference, selectedRead, selectedUnmapped, spine, agreement, selectedState, selectionRelated, ⟨returnTo⟩⟩ :=
        CompatibleMatchTypedSelectionPrefix.Stateful.Certificate.selected_prefix_sized_with_literals certificate ordinary onError allocator literals signatures numericRequirements sites
          catalogValid protocol producer stateBindings definitions registered extended found uniqueExpression represented (environments.extend firstMaps firstWorlds)
          middleRelated agrees (actualTyped.weaken firstWorlds) reference (stillRead.trans read) stillUnmapped coreEval middleState (acquire contextLocation native gate) selected
      have hiddenEq := allocations_same hiddenAllocated sourceHidden
      subst hiddenHeap
      cases selectedBody
      exact ⟨_, selectedStore, selectedMap, selectedWorld, agreement.wrap (.inRight (.inLeft (.inLeft .unit))),
        .fallthrough environment, selectedRelated, firstMaps.trans secondMaps, firstWorlds.trans secondWorlds,
        firstFrame.trans secondFrame, firstMetadata.trans (.of_allocation sourceHidden),
        ⟨returnTo.restore selectedState, protocol.trans firstRelated
          (protocol.trans selectionRelated (returnTo.related selectedState))⟩⟩




/-- Legacy observation through the same actual trace proof. -/
theorem Certificate.preserves_trace_bounded_for
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (validity : SourceSemantics.Context → Prop)
    (literals : IntegerLiteralResolution → Prop)
    (signatures : context.signatures = compilation.signatures)
    (numericRequirements : ∀ numeric, literals numeric → RequirementProves context numeric.requirement numeric.predicate)
    (sites : CompatibleMatchDecision.Certificate.LiteralSites literals certificate)
    (validity_binders : ∀ {binders target}, BindersExtend source.owner context binders target →
      validity context → validity target)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (budget : Nat) {entry : ProtectedExpressionMeaning.Entry}
    (transport : ProtectedExpressionMeaning.Transport entry) (entryBindings : ProtectedExpressionMeaning.Binds entry)
    (expressionMeaning : validity context →
      ∀ child, child < budget → RecursiveNamedBoundedContracts.PreservesAt child (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults entry)
    (armMeaning : RecursiveNamedMatchSourceBounds.ArmPreservesBelowFor (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : RecursiveNamedMatchSourceBounds.DefaultPreservesBelowFor (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (contextValid : validity context)
    {mapping : LocationMap} {world : StoreTyping} {actualContext : Core.Context}
    {environment : Dynamic.Environment} {canonical actual : Environment} {before after : Dynamic.Heap}
    {store : Store} {ξ : Renaming} {contextLocation : Location} {native : NativeFrame}
    {outcome : Dynamic.ControlOutcome}
    (environments : DataHeap.EnvRepresents (CompatibleEquality.storageCatalog compilation.checked.catalog)
      mapping world administrative scope environment canonical ambient.definitions)
    (heaps : CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions mapping world before store)
    (locals : Dynamic.EnvironmentAgrees before context.locals environment)
    (agrees : EnvironmentsAgree ξ canonical actual)
    (actualTyped : RuntimeEnvironmentHasTypes world actual actualContext ambient.definitions)
    (reference : canonical[scope.length + 1 + globals]? = some (.cellRef frame.type contextLocation))
    (read : store.read? contextLocation = some (SourceCoreCallableIndexedFrames.encode frame native))
    (unmapped : contextLocation ∉ mapping)
    (initial : entry scope mapping world before store canonical)
    (trace : RecursiveNamedMatchSourceBounds.TraceBelow budget program context evidence source environment before resolution outcome after) :
    ∃ value finalStore finalMap finalWorld,
      Evaluates actual store (code.rename ξ) value finalStore ∧
      FlowRep (registry := registry) functions finalMap finalWorld faults expected type outcome value ∧
      CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions finalMap finalWorld after finalStore ∧
      LocationMap.Extends mapping finalMap ∧ WorldExtends world finalWorld ∧
      AdministrativePreserved mapping store finalMap finalStore ∧ Dynamic.HeapMetadataExtend before after := by
  let bindings := ProtectedStateMatchBodyContracts.legacyBindings entryBindings
  let producer := ProtectedStateTransition.MarkedAllocation.of_administrative
    (ProtectedStateTransition.Lexical.legacyProtocol entry)
    (ProtectedStateTransition.Lexical.legacyTransport transport) bindings layouts frame (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
  obtain ⟨value, finalStore, finalMap, finalWorld, evaluated, represented, finalHeaps, maps, worlds, frame, metadata, _post⟩ :=
    Stateful.Certificate.preserves_trace_bounded_for onError allocator functions definitions registered extended certificate ordinary unique
      validity literals signatures numericRequirements sites validity_binders catalogValid found uniqueExpression casesTyped defaultTyped budget
      (ProtectedStateTransition.Lexical.legacyProtocol entry) (fun _ _ => True) producer bindings
      (fun _ _ _ => fun _ _ => True.intro)
      (fun valid child smaller => ProtectedStateMatchBodyContracts.legacy_expression_preserves
        transport (expressionMeaning valid child smaller))
      (fun {sourceValue scope environment heap statements bindings finalScope finalEnvironment finalHeap body} scopeEq selected selectedBody {armContext staticFinal facts} extended typed child smaller =>
        ProtectedStateTransition.Lexical.Gated.preserves_of_unguarded
          (ProtectedStateTransition.Lexical.legacyProtocol entry) (fun _ _ => True) functions program evidence
          (ProtectedStateTransition.Lexical.legacy_preserves functions program evidence transport
            (armMeaning scopeEq selected selectedBody extended typed child smaller)))
      (fun {sourceValue scope environment heap statements finalScope finalEnvironment finalHeap body} scopeEq selected selectedBody {staticFinal facts} typed child smaller =>
        ProtectedStateTransition.Lexical.Gated.preserves_of_unguarded
          (ProtectedStateTransition.Lexical.legacyProtocol entry) (fun _ _ => True) functions program evidence
          (ProtectedStateTransition.Lexical.legacy_preserves functions program evidence transport
            (defaultMeaning scopeEq selected selectedBody typed child smaller))) contextValid environments heaps locals agrees actualTyped reference read unmapped ⟨initial⟩ True.intro trace
  exact ⟨value, finalStore, finalMap, finalWorld, evaluated, represented, finalHeaps, maps, worlds, frame, metadata⟩

theorem Certificate.preserves_trace_bounded
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (valid : CompatiblePatternLeaves.ContextValid compilation context)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {solved : List SolvedRequirement} {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (budget : Nat) {entry : ProtectedExpressionMeaning.Entry}
    (transport : ProtectedExpressionMeaning.Transport entry) (entryBindings : ProtectedExpressionMeaning.Binds entry)
    (expressionMeaning : CompatibleExpressionLiterals.ContextValid solved context evidence →
      ∀ child, child < budget → RecursiveNamedBoundedContracts.PreservesAt child (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults entry)
    (armMeaning : RecursiveNamedMatchSourceBounds.ArmPreservesBelow (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : RecursiveNamedMatchSourceBounds.DefaultPreservesBelow (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (contextValid : CompatibleExpressionLiterals.ContextValid solved context evidence)
    {mapping : LocationMap} {world : StoreTyping} {actualContext : Core.Context}
    {environment : Dynamic.Environment} {canonical actual : Environment} {before after : Dynamic.Heap}
    {store : Store} {ξ : Renaming} {contextLocation : Location} {native : NativeFrame}
    {outcome : Dynamic.ControlOutcome}
    (environments : DataHeap.EnvRepresents (CompatibleEquality.storageCatalog compilation.checked.catalog)
      mapping world administrative scope environment canonical ambient.definitions)
    (heaps : CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions mapping world before store)
    (locals : Dynamic.EnvironmentAgrees before context.locals environment)
    (agrees : EnvironmentsAgree ξ canonical actual)
    (actualTyped : RuntimeEnvironmentHasTypes world actual actualContext ambient.definitions)
    (reference : canonical[scope.length + 1 + globals]? = some (.cellRef frame.type contextLocation))
    (read : store.read? contextLocation = some (SourceCoreCallableIndexedFrames.encode frame native))
    (unmapped : contextLocation ∉ mapping)
    (initial : entry scope mapping world before store canonical)
    (trace : RecursiveNamedMatchSourceBounds.TraceBelow budget program context evidence source environment before resolution outcome after) :
    ∃ value finalStore finalMap finalWorld,
      Evaluates actual store (code.rename ξ) value finalStore ∧
      FlowRep (registry := registry) functions finalMap finalWorld faults expected type outcome value ∧
      CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions finalMap finalWorld after finalStore ∧
      LocationMap.Extends mapping finalMap ∧ WorldExtends world finalWorld ∧
      AdministrativePreserved mapping store finalMap finalStore ∧ Dynamic.HeapMetadataExtend before after := by
  exact Certificate.preserves_trace_bounded_for onError allocator functions definitions registered extended certificate ordinary unique (fun context => CompatibleExpressionLiterals.ContextValid solved context evidence) _ valid.signatures
    (fun _ proof => proof) (CompatibleMatchDecision.Certificate.ordinary_sites certificate valid)
    (fun extended proof => valid_binders evidence proof extended) catalogValid
    found uniqueExpression casesTyped defaultTyped budget transport entryBindings expressionMeaning armMeaning defaultMeaning contextValid
    environments heaps locals agrees actualTyped reference read unmapped initial trace

theorem Certificate.preserves_trace_scoped
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (valid : CompatiblePatternLeaves.ContextValid compilation context)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {solved : List SolvedRequirement} {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (expressionMeaning : CompatibleExpressionLiterals.ContextValid solved context evidence →
      TypedGenericExpressionMeaning.Preserves (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults)
    (armMeaning : ArmPreservesScoped functions program context control evidence resolution bodyCertificate expected type scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : DefaultPreservesScoped functions program context control evidence resolution bodyCertificate expected type scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (contextValid : CompatibleExpressionLiterals.ContextValid solved context evidence)
    {mapping : LocationMap} {world : StoreTyping} {actualContext : Core.Context}
    {environment : Dynamic.Environment} {canonical actual : Environment} {before after : Dynamic.Heap}
    {store : Store} {ξ : Renaming} {contextLocation : Location} {native : NativeFrame}
    {outcome : Dynamic.ControlOutcome}
    (environments : DataHeap.EnvRepresents (CompatibleEquality.storageCatalog compilation.checked.catalog)
      mapping world administrative scope environment canonical ambient.definitions)
    (heaps : CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions mapping world before store)
    (locals : Dynamic.EnvironmentAgrees before context.locals environment)
    (agrees : EnvironmentsAgree ξ canonical actual)
    (actualTyped : RuntimeEnvironmentHasTypes world actual actualContext ambient.definitions)
    (reference : canonical[scope.length + 1 + globals]? = some (.cellRef frame.type contextLocation))
    (read : store.read? contextLocation = some (SourceCoreCallableIndexedFrames.encode frame native))
    (unmapped : contextLocation ∉ mapping)
    (trace : DataMatchSourceTrace.Trace program context evidence source environment before resolution outcome after) :
    ∃ value finalStore finalMap finalWorld,
      Evaluates actual store (code.rename ξ) value finalStore ∧
      FlowRep (registry := registry) functions finalMap finalWorld faults expected type outcome value ∧
      CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions finalMap finalWorld after finalStore ∧
      LocationMap.Extends mapping finalMap ∧ WorldExtends world finalWorld ∧
      AdministrativePreserved mapping store finalMap finalStore ∧ Dynamic.HeapMetadataExtend before after := by
  obtain ⟨budget, measured⟩ := RecursiveNamedMatchSourceBounds.trace_has_budget trace
  exact Certificate.preserves_trace_bounded onError allocator functions definitions registered extended certificate ordinary unique valid catalogValid
    found uniqueExpression casesTyped defaultTyped budget (entry := fun _ _ _ _ _ _ => True)
    ⟨by intros; trivial⟩ ⟨by intros; trivial, by intros; trivial⟩
    (by
      intro contextValid child smaller scope id lowered certified node found mapping world administrative environment canonical actual actualContext before store ξ outcome after environments heaps locals agrees typed installed trace
      exact expressionMeaning contextValid certified found environments heaps locals agrees typed trace.sound)
    (RecursiveNamedMatchSourceBounds.ArmPreservesBelow.of_unbounded budget armMeaning)
    (RecursiveNamedMatchSourceBounds.DefaultPreservesBelow.of_unbounded budget defaultMeaning)
    contextValid environments heaps locals agrees actualTyped reference read unmapped True.intro measured

private theorem trace_restored {program : Program} {context : SourceSemantics.Context}
    {evidence : Dynamic.EvidenceEnvironment} {source : TypedSource} {environment : Dynamic.Environment}
    {before after : Dynamic.Heap} {resolution : MatchResolution} {outcome : Dynamic.ControlOutcome}
    (trace : DataMatchSourceTrace.Trace program context evidence source environment before resolution outcome after) :
    Restored environment outcome := by
  cases trace with
  | scrutineeFault => intro next impossible; cases impossible
  | patternFault => intro next impossible; cases impossible
  | arm => exact restored environment _
  | default => exact restored environment _
  | noBranch => intro next same; exact Dynamic.ControlOutcome.fallthrough.inj same.symm

/-- Independent statement execution supplies the finite trace and restores the
 outer lexical context. The enclosing statement induction supplies the child contracts. -/
theorem Stateful.Certificate.preserves_bounded_for
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (validity : SourceSemantics.Context → Prop)
    (literals : IntegerLiteralResolution → Prop)
    (signatures : context.signatures = compilation.signatures)
    (numericRequirements : ∀ numeric, literals numeric → RequirementProves context numeric.requirement numeric.predicate)
    (sites : CompatibleMatchDecision.Certificate.LiteralSites literals certificate)
    (validity_binders : ∀ {binders target}, BindersExtend source.owner context binders target →
      validity context → validity target)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (budget size : Nat) (bounded : size ≤ budget) {Records : Type v}
    (protocol : ProtectedStateTransition.Protocol.{u, v} Records)
    (guard : Location → NativeFrame → Prop)
    (producer : ProtectedStateTransition.MarkedAllocation.Producer protocol layouts frame
      (CompatibleAmbientHeap.payloadModel compilation.checked registry functions))
    (stateBindings : ProtectedStateTransition.Bindings protocol)
    (acquire : ∀ location native, guard location native →
      ProtectedStateTransition.OrdinaryAllocation.ReadyAt producer.toOrdinary location native)
    (expressionMeaning : validity context →
      ∀ child, child < budget → ProtectedStateTransition.PreservesAt protocol (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults child)
    (armMeaning : RecursiveNamedMatchSourceBounds.Stateful.ArmPreservesBelowFor protocol guard functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : RecursiveNamedMatchSourceBounds.Stateful.DefaultPreservesBelowFor protocol guard functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults)) :
    RecursiveNamedMatchSourceBounds.Stateful.Head.HeadPreservesAtFor protocol guard functions program evidence validity (values := compilation.values) (source := source)
      (context := context) (administrative := administrative) (frameLayout := frame)
      (globals := globals) (registry := registry) (faults := faults) size (scope := scope) id expected type code := by
  intro contextValid mapping world actualContext environment canonical actual before after store ξ contextLocation native outcome finalContext
    environments heaps locals agrees actualTyped reference read unmapped initial gate executed
  have sourceTrace : finalContext = context ∧
      RecursiveNamedMatchSourceBounds.TraceBelow budget program context evidence source environment before resolution outcome after := by
    cases certificate with
    | matchWith read _ form =>
      exact RecursiveNamedMatchSourceBounds.of_outcome unique (lookupStatement?_complete unique (read_contains read)) form bounded executed
  exact ⟨sourceTrace.1, trace_restored sourceTrace.2.sound,
    Stateful.Certificate.preserves_trace_bounded_for onError allocator functions definitions registered extended certificate ordinary unique validity literals signatures numericRequirements sites validity_binders catalogValid
      found uniqueExpression casesTyped defaultTyped budget protocol guard producer stateBindings acquire expressionMeaning armMeaning defaultMeaning contextValid
      environments heaps locals agrees actualTyped reference read unmapped initial gate sourceTrace.2⟩



/-- Legacy observation through the same actual head producer. -/
theorem Certificate.preserves_bounded_for
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (validity : SourceSemantics.Context → Prop)
    (literals : IntegerLiteralResolution → Prop)
    (signatures : context.signatures = compilation.signatures)
    (numericRequirements : ∀ numeric, literals numeric → RequirementProves context numeric.requirement numeric.predicate)
    (sites : CompatibleMatchDecision.Certificate.LiteralSites literals certificate)
    (validity_binders : ∀ {binders target}, BindersExtend source.owner context binders target →
      validity context → validity target)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (budget size : Nat) (bounded : size ≤ budget) {entry : ProtectedExpressionMeaning.Entry}
    (transport : ProtectedExpressionMeaning.Transport entry) (entryBindings : ProtectedExpressionMeaning.Binds entry)
    (expressionMeaning : validity context →
      ∀ child, child < budget → RecursiveNamedBoundedContracts.PreservesAt child (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults entry)
    (armMeaning : RecursiveNamedMatchSourceBounds.ArmPreservesBelowFor (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : RecursiveNamedMatchSourceBounds.DefaultPreservesBelowFor (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget validity scope
      (source := source) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults)) :
    RecursiveNamedMatchSourceBounds.Head.HeadPreservesAtFor (entry := entry) functions program evidence validity (values := compilation.values) (source := source)
      (context := context) (administrative := administrative) (frameLayout := frame)
      (globals := globals) (registry := registry) (faults := faults) size (scope := scope) id expected type code := by
  intro contextValid mapping world actualContext environment canonical actual before after store ξ contextLocation native outcome finalContext
    environments heaps locals agrees actualTyped reference read unmapped initial executed
  let bindings := ProtectedStateMatchBodyContracts.legacyBindings entryBindings
  let producer := ProtectedStateTransition.MarkedAllocation.of_administrative
    (ProtectedStateTransition.Lexical.legacyProtocol entry)
    (ProtectedStateTransition.Lexical.legacyTransport transport) bindings layouts frame (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
  obtain ⟨sameContext, restored, value, finalStore, finalMap, finalWorld, evaluated, represented, finalHeaps, maps, worlds, frame, metadata, _post⟩ :=
    Stateful.Certificate.preserves_bounded_for onError allocator functions definitions registered extended certificate ordinary unique
      validity literals signatures numericRequirements sites validity_binders catalogValid found uniqueExpression casesTyped defaultTyped budget size bounded
      (ProtectedStateTransition.Lexical.legacyProtocol entry) (fun _ _ => True) producer bindings
      (fun _ _ _ => fun _ _ => True.intro)
      (fun valid child smaller => ProtectedStateMatchBodyContracts.legacy_expression_preserves
        transport (expressionMeaning valid child smaller))
      (fun {sourceValue scope environment heap statements bindings finalScope finalEnvironment finalHeap body} scopeEq selected selectedBody {armContext staticFinal facts} extended typed child smaller =>
        ProtectedStateTransition.Lexical.Gated.preserves_of_unguarded
          (ProtectedStateTransition.Lexical.legacyProtocol entry) (fun _ _ => True) functions program evidence
          (ProtectedStateTransition.Lexical.legacy_preserves functions program evidence transport
            (armMeaning scopeEq selected selectedBody extended typed child smaller)))
      (fun {sourceValue scope environment heap statements finalScope finalEnvironment finalHeap body} scopeEq selected selectedBody {staticFinal facts} typed child smaller =>
        ProtectedStateTransition.Lexical.Gated.preserves_of_unguarded
          (ProtectedStateTransition.Lexical.legacyProtocol entry) (fun _ _ => True) functions program evidence
          (ProtectedStateTransition.Lexical.legacy_preserves functions program evidence transport
            (defaultMeaning scopeEq selected selectedBody typed child smaller))) contextValid environments heaps locals agrees actualTyped reference read unmapped ⟨initial⟩ True.intro executed
  exact ⟨sameContext, restored, value, finalStore, finalMap, finalWorld, evaluated, represented, finalHeaps, maps, worlds, frame, metadata⟩

theorem Certificate.preserves_bounded
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (valid : CompatiblePatternLeaves.ContextValid compilation context)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {solved : List SolvedRequirement} {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (budget size : Nat) (bounded : size ≤ budget) {entry : ProtectedExpressionMeaning.Entry}
    (transport : ProtectedExpressionMeaning.Transport entry) (entryBindings : ProtectedExpressionMeaning.Binds entry)
    (expressionMeaning : CompatibleExpressionLiterals.ContextValid solved context evidence →
      ∀ child, child < budget → RecursiveNamedBoundedContracts.PreservesAt child (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults entry)
    (armMeaning : RecursiveNamedMatchSourceBounds.ArmPreservesBelow (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : RecursiveNamedMatchSourceBounds.DefaultPreservesBelow (entry := entry) functions program context control evidence resolution bodyCertificate expected type budget scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults)) :
    RecursiveNamedMatchSourceBounds.Head.HeadPreservesAt (entry := entry) functions program evidence (values := compilation.values) (source := source)
      (context := context) (solved := solved) (administrative := administrative) (frameLayout := frame)
      (globals := globals) (registry := registry) (faults := faults) size (scope := scope) id expected type code := by
  exact Certificate.preserves_bounded_for onError allocator functions definitions registered extended certificate ordinary unique (fun context => CompatibleExpressionLiterals.ContextValid solved context evidence) _ valid.signatures
    (fun _ proof => proof) (CompatibleMatchDecision.Certificate.ordinary_sites certificate valid)
    (fun extended proof => valid_binders evidence proof extended) catalogValid
    found uniqueExpression casesTyped defaultTyped budget size bounded transport entryBindings expressionMeaning armMeaning defaultMeaning

theorem Certificate.preserves_scoped
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (valid : CompatiblePatternLeaves.ContextValid compilation context)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {solved : List SolvedRequirement} {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (expressionMeaning : CompatibleExpressionLiterals.ContextValid solved context evidence →
      TypedGenericExpressionMeaning.Preserves (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults)
    (armMeaning : ArmPreservesScoped functions program context control evidence resolution bodyCertificate expected type scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : DefaultPreservesScoped functions program context control evidence resolution bodyCertificate expected type scope
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults)) :
    TypedLexicalWhile.HeadPreserves functions program evidence (values := compilation.values) (source := source)
      (context := context) (solved := solved) (administrative := administrative) (frameLayout := frame)
      (globals := globals) (registry := registry) (faults := faults) (scope := scope) id expected type code := by
  intro contextValid mapping world actualContext environment canonical actual before after store ξ contextLocation native outcome finalContext
    environments heaps locals agrees actualTyped reference read unmapped executed
  have sourceTrace : finalContext = context ∧
      DataMatchSourceTrace.Trace program context evidence source environment before resolution outcome after := by
    cases certificate with
    | matchWith read _ form => exact DataMatchSourceTrace.of_outcome unique (read_contains read) form executed
  exact ⟨sourceTrace.1, trace_restored sourceTrace.2,
    Certificate.preserves_trace_scoped onError allocator functions definitions registered extended certificate ordinary unique valid catalogValid
      found uniqueExpression casesTyped defaultTyped expressionMeaning armMeaning defaultMeaning contextValid
      environments heaps locals agrees actualTyped reference read unmapped sourceTrace.2⟩

theorem Certificate.preserves_trace
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (valid : CompatiblePatternLeaves.ContextValid compilation context)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {solved : List SolvedRequirement} {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (expressionMeaning : CompatibleExpressionLiterals.ContextValid solved context evidence →
      TypedGenericExpressionMeaning.Preserves (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults)
    (armMeaning : ArmPreserves functions program context control evidence resolution bodyCertificate expected type
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : DefaultPreserves functions program context control evidence resolution bodyCertificate expected type
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (contextValid : CompatibleExpressionLiterals.ContextValid solved context evidence)
    {mapping : LocationMap} {world : StoreTyping} {actualContext : Core.Context}
    {environment : Dynamic.Environment} {canonical actual : Environment} {before after : Dynamic.Heap}
    {store : Store} {ξ : Renaming} {contextLocation : Location} {native : NativeFrame}
    {outcome : Dynamic.ControlOutcome}
    (environments : DataHeap.EnvRepresents (CompatibleEquality.storageCatalog compilation.checked.catalog)
      mapping world administrative scope environment canonical ambient.definitions)
    (heaps : CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions mapping world before store)
    (locals : Dynamic.EnvironmentAgrees before context.locals environment)
    (agrees : EnvironmentsAgree ξ canonical actual)
    (actualTyped : RuntimeEnvironmentHasTypes world actual actualContext ambient.definitions)
    (reference : canonical[scope.length + 1 + globals]? = some (.cellRef frame.type contextLocation))
    (read : store.read? contextLocation = some (SourceCoreCallableIndexedFrames.encode frame native))
    (unmapped : contextLocation ∉ mapping)
    (trace : DataMatchSourceTrace.Trace program context evidence source environment before resolution outcome after) :
    ∃ value finalStore finalMap finalWorld,
      Evaluates actual store (code.rename ξ) value finalStore ∧
      FlowRep (registry := registry) functions finalMap finalWorld faults expected type outcome value ∧
      CompatibleAmbientHeap.HeapRepresents compilation.checked registry functions finalMap finalWorld after finalStore ∧
      LocationMap.Extends mapping finalMap ∧ WorldExtends world finalWorld ∧
      AdministrativePreserved mapping store finalMap finalStore ∧ Dynamic.HeapMetadataExtend before after := by
  exact Certificate.preserves_trace_scoped onError allocator functions definitions registered extended certificate ordinary unique valid catalogValid
    found uniqueExpression casesTyped defaultTyped expressionMeaning (armMeaning.scoped scope) (defaultMeaning.scoped scope) contextValid
    environments heaps locals agrees actualTyped reference read unmapped trace

theorem Certificate.preserves
    {compilation : SourceCoreCompatibleDataMatches.Context}
    {layouts : SourceCoreAllocationLayouts.Prepared} {owner : SourceSpecialization.SpecializationKey}
    {active : TypeSystem.Substitution} {frame : SourceCoreCallableIndexedFrames.Layout} {globals : Nat}
    (onError : SourceCoreAllocationLayouts.Error → SourceCoreBasic.Error)
    (allocator : compilation.sourceCells = some (SourceCoreCallableIndexedAllocationFrames.allocator frame globals
      (layouts.allocatorAt owner active onError)))
    {ambient : AmbientDefinitions compilation.checked.catalog.definitions}
    (functions : FunctionModel compilation.checked.catalog ambient)
    (definitions : layouts.definitions = ambient.definitions) (registered : frame.Registered ambient.definitions)
    {registry : SourceCoreRawMetadata.Registry}
    (extended : SourceCoreRawMetadata.Extends compilation.values.registry registry)
    {source : TypedSource} {context : SourceSemantics.Context} {control : ControlContext}
    {program : Program} {evidence : Dynamic.EvidenceEnvironment} {scope : Scope}
    {id : StatementId} {resolution : MatchResolution} {expected : TypeSystem.Ty} {type : Ty} {reason : Word}
    {expressionCertificate : ExpressionCertificate} {bodyCertificate : BodyCertificate} {code : Expr}
    (certificate : CompatibleMatchCertificates.Certificate compilation source scope id resolution type reason
      expressionCertificate bodyCertificate code)
    (ordinary : CompatibleMatchSelectionPrefix.Ordinary certificate)
    (unique : NodeOccurrencesUnique source)
    (valid : CompatiblePatternLeaves.ContextValid compilation context)
    (catalogValid : SignatureCatalogWellFormed compilation.checked.signatures)
    {node : ExpressionNode} (found : source.lookupExpression? resolution.scrutinee = some node)
    {lowered : SourceCoreBasic.LoweredExpr}
    (uniqueExpression : ∀ other, expressionCertificate scope resolution.scrutinee other → other = lowered)
    {caseFacts : List BodyFacts}
    (casesTyped : MatchCasesHaveType source control context node.type resolution.cases caseFacts)
    (defaultTyped : ∀ {statements}, resolution.defaultBody = some statements →
      ∃ finalContext facts, StatementsHaveType source control context statements finalContext facts)
    {solved : List SolvedRequirement} {administrative : Core.Context} {faults : FunctionCalls.FaultRep}
    (expressionMeaning : CompatibleExpressionLiterals.ContextValid solved context evidence →
      TypedGenericExpressionMeaning.Preserves (CompatibleAmbientHeap.payloadModel compilation.checked registry functions)
        program context evidence source expressionCertificate faults)
    (armMeaning : ArmPreserves functions program context control evidence resolution bodyCertificate expected type
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults))
    (defaultMeaning : DefaultPreserves functions program context control evidence resolution bodyCertificate expected type
      (source := source) (solved := solved) (administrative := administrative) (frame := frame) (globals := globals)
      (registry := registry) (faults := faults)) :
    TypedLexicalWhile.HeadPreserves functions program evidence (values := compilation.values) (source := source)
      (context := context) (solved := solved) (administrative := administrative) (frameLayout := frame)
      (globals := globals) (registry := registry) (faults := faults) (scope := scope) id expected type code := by
  exact Certificate.preserves_scoped onError allocator functions definitions registered extended certificate ordinary unique valid catalogValid
    found uniqueExpression casesTyped defaultTyped expressionMeaning (armMeaning.scoped scope) (defaultMeaning.scoped scope)

end Solcore.SourceSemantics.CoreLowering.CompatibleMatchPreservation
