import Solcore.SourceSemantics.CoreLowering.EmittedImperativeMatchTokenCertificates
import Solcore.SourceSemantics.CoreLowering.RecursiveNamedCatalogRuntimeProfileFactory

/-! Actual cached Header extraction retains unary token provenance beside
the diagnostic plan generated by its original compiler traversal. The complete
receipt and own diagnostic equation belong to this actual parameter entry. -/
set_option autoImplicit false
set_option maxHeartbeats 2400000
namespace Solcore.SourceSemantics.CoreLowering.RecursiveNamedCatalogRuntimeProfileFactory
open Core Frontend SourceInference GeneralHeap ReadOnly CompatiblePayload
open CallableAncestryPairedLookup RecursiveNamedCatalog RecursiveNamedCatalogInvocationBounds
open RecursiveNamedCatalogNativeContexts NativeExpressionContextSupport
variable {checked : Checked} {base : Base checked}
  {prepared : SourceCoreCallableIndexedAncestry.Prepared base} {values : SourceCoreCompatibleValues.Context}
  {ambient : AmbientDefinitions values.checked.catalog.definitions} {program : Program}
  {headers : Inventory prepared values ambient.definitions program}
  {header : Header prepared values ambient.definitions program}
  {compilation : SourceCoreFunctions.Context} {expressionSyntax : ExpressionId → Prop}
  {administrative : Core.Context} {authenticated : Bool} {diagnosticPolicy : AssignmentDiagnosticPolicy}

variable {certificates : SourceSemantics.Context → GenericExpressionMeaning.Certificate}
  {locations : Locations} {functions : FunctionModel values.checked.catalog ambient}
  {registry : SourceCoreRawMetadata.Registry} {arguments : List Dynamic.Value} {before : Dynamic.Heap}
  {initialStore : Store} {initialMap : LocationMap} {initialWorld : StoreTyping}
  {actualContext : Core.Context} {actual : Environment} {ξ : Renaming} {frameLocation : Location}
  {current : CallableIndexedHistory.NativeFrame} {ghost : CallableIndexedHistory.GhostFrame}
  {tracked : Bool} {suffix : Core.Context}
  (cachedTyped : HasType (base.globals.map (·.referenceType) ++ .cell prepared.layout.frame.type :: suffix)
    (.lambda header.named.signature.parameterType (LanguageResult.resultType header.named.signature.resultType) header.code)
    header.named.signature.functionType ambient.definitions)
  (support : supported (.lambda header.named.signature.parameterType
    (LanguageResult.resultType header.named.signature.resultType) header.code) (base.globals.length + 1) = true)
  (complete : Complete headers) (globals : header.globals = base.globals.length)
  (entry : BodyState headers locations 0 functions registry header arguments before initialStore initialMap initialWorld
    administrative actualContext actual ξ frameLocation current ghost)

include cachedTyped support complete globals entry in
/-- The actual cached entry selects the original static traversal, retaining
its genuine emitted diagnostics rather than an arbitrary receipt predicate. -/
theorem extract_source_for_with_tokens
    (inputs : InputsFor certificates tracked diagnosticPolicy header expressionSyntax
      (SourceCoreCompatibleCatalog.packTypes (header.bindings.map Prod.snd) :: administrative)) :
    Nonempty (EmittedDiagnosticTokenPlan.Produced inputs.factory inputs.invalidUnary
      (ReceiptFor certificates diagnosticPolicy header expressionSyntax
        (SourceCoreCompatibleCatalog.packTypes (header.bindings.map Prod.snd) :: administrative))
      (fun receipt => receipt.extracted.diagnostics)) := by
  have typed := canonical_cached complete globals cachedTyped support entry
  obtain ⟨flow, generated, produced, _⟩ := GenericImperativeMatch.extraction_of_typed_body_with_tokens true diagnosticPolicy
    inputs.factory inputs.matchPolicy inputs.matchValues inputs.matchDefinitions inputs.matchAllocator inputs.matchChildStatic
    inputs.readPolicy inputs.binderPolicy inputs.allocationPolicy inputs.expressions inputs.assignments inputs.unaryPolicy
    header.unique inputs.assignmentExpressions inputs.syntaxTree
    (RecursiveNamedSourceContextFacts.header_typeVariables header) (RecursiveNamedSourceContextFacts.header_residual header)
    inputs.sourceSignatures inputs.declarations inputs.projection inputs.accepted typed
  rw [inputs.matchLedger] at produced
  exact ⟨⟨⟨⟨inputs.accepted, inputs.projection, inputs.sourceSignatures, flow, generated, produced.original⟩,
    produced.plan, produced.equation⟩, produced.tokens⟩⟩

include cachedTyped support complete globals entry in
/-- The existing runtime certificate specialization preserves the whole
actual emitted receipt and its exact diagnostic plan. -/
theorem extract_source_with_tokens
    (inputs : InputsWith authenticated tracked diagnosticPolicy headers header compilation expressionSyntax
      (SourceCoreCompatibleCatalog.packTypes (header.bindings.map Prod.snd) :: administrative)) :
    Nonempty (EmittedDiagnosticTokenPlan.Produced inputs.factory inputs.invalidUnary
      (ReceiptWith authenticated diagnosticPolicy headers header compilation expressionSyntax
        (SourceCoreCompatibleCatalog.packTypes (header.bindings.map Prod.snd) :: administrative))
      (fun receipt => receipt.extracted.diagnostics)) := by
  obtain ⟨produced⟩ := extract_source_for_with_tokens cachedTyped support complete globals entry inputs.to_for
  exact ⟨⟨⟨⟨produced.original.accepted, produced.original.projection, produced.original.signatures,
    produced.original.flow, produced.original.generated, produced.original.extracted⟩,
    produced.plan, produced.equation⟩, produced.tokens⟩⟩

end Solcore.SourceSemantics.CoreLowering.RecursiveNamedCatalogRuntimeProfileFactory
