import Solcore.Frontend.ProgramIdentity
import Solcore.Frontend.ProgramEnvironmentProperties
import Solcore.Frontend.ProgramSignaturesProperties
import Solcore.Frontend.ProgramSignatureFormation
import Solcore.Frontend.TraitResolutionProperties
import Solcore.Frontend.ProgramChecking
import Solcore.Frontend.ExecutableImplMethods
import Solcore.Frontend.SourceStageAnalysis
import Solcore.Frontend.SourceStagedValue
import Solcore.Frontend.SourceSpecialization
import Solcore.Frontend.SourceSpecializationWorklist
import Solcore.Frontend.SourceCoreElaboration
import Solcore.Frontend.SourceCoreLocalCell
import Solcore.Frontend.SourceCoreBasic
import Solcore.Frontend.SourceCoreControl
import Solcore.Frontend.SourceCorePrimitive
import Solcore.Frontend.SourceCoreLoops
import Solcore.Frontend.SourceCoreCalls
import Solcore.Frontend.SourceCoreProgramFaultSites
import Solcore.Frontend.SourceCoreRecursiveEntry
import Solcore.Frontend.SourceCoreFunctionTypes
import Solcore.Frontend.SourceCoreFunctions
import Solcore.Frontend.SourceCoreFunctionEntry
import Solcore.Frontend.SourceCoreFaultSites
import Solcore.Frontend.SourceCoreBasicEntry
import Solcore.Frontend.SourceTypedRuntime
import Solcore.Frontend.SourceCoreDirectLinking
import Solcore.Frontend.SourceTypedStaticSafetyProperties
import Solcore.Frontend.SourceProgramExecution
import Solcore.Frontend.SourceCompiler

import Solcore.Frontend.SourceCoreAssignments
import Solcore.Frontend.SourceCoreAssignmentFaultSites
import Solcore.Frontend.SourceCoreRuntimeFaultSites
import Solcore.Frontend.SourceCoreAssignmentPolicy

import Solcore.Frontend.SourceCoreDataCatalog

import Solcore.Frontend.SourceCoreScalar
import Solcore.Frontend.SourceCoreInteger
import Solcore.Frontend.SourceCoreGeneralEntry
import Solcore.Frontend.SourceCoreGeneralFunctions
import Solcore.Frontend.SourceCorePlanCatalog
import Solcore.Frontend.SourceCoreDataValues
import Solcore.Frontend.SourceCoreSession

/-! Current whole-program source pipeline and preservation results. -/
