import Solcore.Frontend.ProgramIdentity
import Solcore.Frontend.ProgramEnvironmentProperties
import Solcore.Frontend.ProgramSignaturesProperties
import Solcore.Frontend.ProgramSignatureFormation
import Solcore.Frontend.TraitResolutionProperties
import Solcore.Frontend.ProgramChecking
import Solcore.Frontend.ExecutableImplMethods
import Solcore.Frontend.SourceStageAnalysis
import Solcore.Frontend.SourceStagedValue
import Solcore.Frontend.SourceSpecialization
import Solcore.Frontend.SourceSpecializationWorklist
import Solcore.Frontend.SourceCoreElaboration
import Solcore.Frontend.SourceCoreLocalCell
import Solcore.Frontend.SourceTypedRuntime
import Solcore.Frontend.SourceCoreDirectLinking
import Solcore.Frontend.SourceTypedStaticSafetyProperties
import Solcore.Frontend.SourceProgramExecution
import Solcore.Frontend.SourceCompiler

/-! Current whole-program source pipeline and preservation results. -/
