import Solcore.SourceSemantics.CoreLowering.DataPayloadUpdatePaths
import Solcore.SourceSemantics.CoreLowering.DataPayloadEncoding
import Solcore.SourceSemantics.CoreLowering.DataPayloadCatalog

/-! Public encoding and actual route preparation supply a nested read tree.
All equality/default evaluations are generated by the semantic proof. -/
set_option autoImplicit false
set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
namespace Tests.SourceCoreDataPayloadPaths
open Solcore Solcore.Core Solcore.Frontend Solcore.Frontend.SourceInference
open Solcore.SourceSemantics Solcore.SourceSemantics.CoreLowering
open DataPayload DataPayloadEncoding DataPayloadReadPaths SourceCoreDataPlaces DataPlaceMappingIndex
private def innerType : TypeSystem.Ty := .mapping .integer .integer
private def outerType : TypeSystem.Ty := .mapping .integer innerType
private def innerLayout : Core.OrderedMapping.Layout := ⟨.integer, .integer, ⟨0⟩⟩
private def outerLayout : Core.OrderedMapping.Layout := ⟨.integer, innerLayout.type, ⟨1⟩⟩
private def catalog : SourceCoreDataCatalog.Catalog := { entries := [
  { sourceType := innerType, definition := some innerLayout.definition },
  { sourceType := outerType, definition := some outerLayout.definition }] }
private def checked : SourceCoreDataCatalog.Checked := ⟨catalog, Core.DataEnvironment.isWellFormed_sound (by decide)⟩
private def signatures : ProgramSignatures := ⟨[], [], [], [], [], []⟩
private def context : SourceCoreDataValues.Context := ⟨checked, signatures⟩
private def functions : GenericHeap.PayloadModel catalog where
  Represents := fun _ _ _ _ _ _ => False
  projection := False.elim
  runtime_hasType := False.elim
  extend := fun impossible _ _ => False.elim impossible
private theorem observations : FunctionObservations catalog signatures functions (fun _ _ => False) :=
  fun impossible => False.elim impossible
private theorem faithful : DataEquality.IdentityFaithful (fun _ _ => False) := by
  constructor <;> intros <;> contradiction
private theorem layouts : CatalogLayouts catalog := by
  apply CatalogLayouts.of_entries
  intro id entry selected
  rcases id with ⟨index⟩
  cases index with
  | zero => cases selected; exact ⟨.integer, .integer, rfl, rfl, ⟨.integer, .integer, rfl⟩⟩
  | succ index => cases index with
    | zero => cases selected; exact ⟨.integer, .namedData ⟨0⟩, rfl, rfl, ⟨.integer, .namedData (by rfl), rfl⟩⟩
    | succ index => simp [catalog] at selected
private theorem except_get {α ε : Type} (result : Except ε α) (positive : result.toOption.isSome = true) :
    result = .ok (result.toOption.get positive) := by
  cases result with
  | error => simp [Except.toOption] at positive
  | ok => rfl
private theorem comparisonExists : (SourceCoreDataEquality.prepare 20 checked .integer).toOption.isSome = true := by cbv
private def comparison := (SourceCoreDataEquality.prepare 20 checked .integer).toOption.get comparisonExists
private theorem comparisonGenerated : SourceCoreDataEquality.prepare 20 checked .integer = .ok comparison := except_get _ comparisonExists
private theorem innerDefaultExists : (SourceCoreDefaultValue.prepare (innerType.size + 1) checked innerType).toOption.isSome = true := by cbv
private def innerDefault := (SourceCoreDefaultValue.prepare (innerType.size + 1) checked innerType).toOption.get innerDefaultExists
private theorem innerDefaultGenerated : SourceCoreDefaultValue.prepare (innerType.size + 1) checked innerType = .ok innerDefault := except_get _ innerDefaultExists
private theorem integerDefaultExists : (SourceCoreDefaultValue.prepare (TypeSystem.Ty.integer.size + 1) checked .integer).toOption.isSome = true := by cbv
private def integerDefault := (SourceCoreDefaultValue.prepare (TypeSystem.Ty.integer.size + 1) checked .integer).toOption.get integerDefaultExists
private theorem integerDefaultGenerated : SourceCoreDefaultValue.prepare (TypeSystem.Ty.integer.size + 1) checked .integer = .ok integerDefault := except_get _ integerDefaultExists
private def moduleId : Workspace.ModuleId := ⟨.main, ⟨[⟨"payload_path", by decide⟩], by decide⟩⟩
private def owner : Resolved.DeclarationId := ⟨moduleId, 0⟩
private def keyId (index : Nat) : ExpressionId := ⟨⟨owner, index⟩⟩
private def innerIndex : PreparedIndex := ⟨innerLayout, keyId 1, 1, comparison.expression, integerDefault.expression, Word.zero⟩
private def outerIndex : PreparedIndex := ⟨outerLayout, keyId 0, 0, comparison.expression, innerDefault.expression, Word.zero⟩
private def route : Route := ⟨outerType, outerLayout.type, .integer,
  [.index outerLayout (keyId 0) innerType, .index innerLayout (keyId 1) .integer], some outerLayout⟩
private def prepared : Prepared := ⟨route, [.index outerIndex, .index innerIndex], [(keyId 0, .integer), (keyId 1, .integer)], Word.zero⟩
private theorem accepted : prepare checked 20 route Word.zero (fun _ => Word.zero) = .ok prepared := by
  have outer : checked.catalog.entries[1]? = some ⟨outerType, some outerLayout.definition, []⟩ := rfl
  have inner : checked.catalog.entries[0]? = some ⟨innerType, some innerLayout.definition, []⟩ := rfl
  have innerGenerated := innerDefaultGenerated
  simp only [innerType] at innerGenerated
  simp [prepare, route, innerLayout, outerLayout, outer, inner, outerType, innerType,
    comparisonGenerated, innerGenerated, integerDefaultGenerated,
    prepared, innerIndex, outerIndex, bind, Except.bind, pure, Except.pure, Except.mapError]
private def publicValue : SourceCoreDataValues.Value := .mapping .integer innerType [
  (.integer 9, .mapping .integer .integer [(.integer 7, .integer 11), (.integer 7, .integer 22)])]
private def sourceValue : Dynamic.Value := .mapping .integer innerType [
  (.integer 9, .mapping .integer .integer [(.integer 7, .integer 11), (.integer 7, .integer 22)])]
private def coreValue : Value := Core.OrderedMapping.encode outerLayout [
  (.integer 9, Core.OrderedMapping.encode innerLayout [(.integer 7, .integer 11), (.integer 7, .integer 22)])]
private theorem meaning : Means publicValue sourceValue :=
  .mapping (.prepend (.integer 9) (.mapping (.prepend (.integer 7) (.integer 11) (.prepend (.integer 7) (.integer 22) .empty))) .empty)
private theorem encoded : SourceCoreDataValues.encode 40 context outerType publicValue = .ok coreValue := by cbv
private theorem represented : ValueRep catalog signatures functions [] [] outerType sourceValue coreValue outerLayout.type :=
  encodes_represents_at layouts meaning rfl (SourceCoreDataValues.encodes_of_encode encoded)
private def keys : List Value := [.integer 9, .integer 7]
private def projections : List Dynamic.EvaluatedProjection := [.index (.integer 9), .index (.integer 7)]
private theorem path : Path checked signatures functions [] [] keys outerType outerLayout.type prepared.steps projections .integer .integer 6 := by
  apply Path.index (count := 3) (Index.of_generated comparisonGenerated innerDefaultGenerated rfl rfl) rfl rfl (.integer 9) rfl
  apply Path.index (count := 0) (Index.of_generated comparisonGenerated integerDefaultGenerated rfl rfl) rfl rfl (.integer 7) rfl
  exact .nil rfl
private theorem sourceRead : Dynamic.ProjectionsRead (some sourceValue) projections (some (.integer 11)) :=
  .indexFound (.head ⟨rfl, .integer 9⟩) (.indexFound (.head ⟨rfl, .integer 7⟩) .nil)

/-- The source read, full public payload, and actual helper preparations imply
finite Core completion. No recursive read-tree nodes are supplied by hand. -/
example : prepare checked 20 route Word.zero (fun _ => Word.zero) = .ok prepared ∧
    ∃ finalStore required, ∀ fuel, required ≤ fuel →
      runStateful fuel (.initial (select prepared prepared.steps (.var 0) (.var 1))
        [coreValue, DataPatternValues.packValues keys] [.integer 900]) =
        .done (.inRight .word (.inRight .unit (.integer 11))) finalStore := by
  have tree := path.read_tree observations layouts prepared represented sourceRead
  obtain ⟨leaf, finalStore, admin, read, represented, evaluated, extended, counted⟩ :=
    tree.preserves faithful rfl [coreValue, DataPatternValues.packValues keys] [.integer 900] (.var 0) (.var 1) (.var rfl) (.var rfl)
  cases represented with
  | integer =>
    obtain ⟨required, complete⟩ := evaluation_runStateful_complete_with_sufficient_fuel evaluated
    exact ⟨accepted, finalStore, required, complete⟩

private def updatedSource : Dynamic.Value := .mapping .integer innerType [
  (.integer 9, .mapping .integer .integer [(.integer 7, .integer 55), (.integer 7, .integer 22)])]
private def updatedCore : Value := Core.OrderedMapping.encode outerLayout [
  (.integer 9, Core.OrderedMapping.encode innerLayout [(.integer 7, .integer 55), (.integer 7, .integer 22)])]
private theorem sourceUpdate : Dynamic.ProjectionsUpdate (fun _ new => new = Dynamic.Value.integer 55)
    (some sourceValue) projections updatedSource :=
  .indexFound (.head ⟨rfl, .integer 9⟩)
    (.indexFound (.head ⟨rfl, .integer 7⟩) (.leaf rfl) (.update (.head ⟨rfl, .integer 7⟩)))
    (.update (.head ⟨rfl, .integer 9⟩))

/-- Complete keys and untouched duplicate entries survive reconstruction.
The actual recursive helper evaluations are consequences of the theorem. -/
example : ∃ output finalStore admin required,
    ValueRep catalog signatures functions [] [] outerType updatedSource output outerLayout.type ∧
    finalStore = [.integer 900] ++ admin ∧ admin.length = 12 ∧
    ∀ fuel, required ≤ fuel → runStateful fuel
      (.initial (update prepared prepared.steps outerLayout.type (.var 0) (.var 1) (.var 2))
        [coreValue, DataPatternValues.packValues keys, .integer 55] [.integer 900]) = .done (.inRight .word output) finalStore := by
  obtain ⟨output, finalStore, admin, represented, evaluated, extended, counted⟩ :=
    path.update_preserves observations faithful layouts prepared rfl represented (.integer 55) sourceUpdate
      [coreValue, DataPatternValues.packValues keys, .integer 55] [.integer 900] (.var 0) (.var 1) (.var 2)
      (.var rfl) (.var rfl) (.var rfl)
  obtain ⟨required, complete⟩ := evaluation_runStateful_complete_with_sufficient_fuel evaluated
  exact ⟨output, finalStore, admin, required, represented, extended, counted, complete⟩

example : (match runStateful 2000
    (.initial (update prepared prepared.steps outerLayout.type (.var 0) (.var 1) (.var 2))
      [coreValue, DataPatternValues.packValues keys, .integer 55] [.integer 900]) with
    | .done value _ => some value
    | _ => none) = some (.inRight .word updatedCore) := by cbv

end Tests.SourceCoreDataPayloadPaths
