import Solcore.Syntax.Parser.Expression.AtomProperties

/-! External consumers for canonical Core expression-atom contracts. -/

set_option autoImplicit false

namespace Tests

open Solcore.Syntax.Parser

example := @ExpressionAtomInternals.expressionName_validFor
example := @ExpressionAtomInternals.expressionName_preservesTokenWindow
example := @ExpressionAtomInternals.expressionName_preservesTokensOnSuccess
example := @ExpressionAtomInternals.expressionName_ok_state_shape
example := @ExpressionAtomInternals.expressionName_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.expressionName_cursor_lt_onSuccess
example := @ExpressionAtomInternals.expressionName_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.literalExpression_validFor
example := @ExpressionAtomInternals.literalExpression_preservesTokenWindow
example := @ExpressionAtomInternals.literalExpression_preservesTokensOnSuccess
example := @ExpressionAtomInternals.literalExpression_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.literalExpression_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.identifierExpression_validFor
example := @ExpressionAtomInternals.identifierExpression_preservesTokenWindow
example := @ExpressionAtomInternals.identifierExpression_preservesTokensOnSuccess
example := @ExpressionAtomInternals.identifierExpression_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.identifierExpression_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.proxyExpression_validFor
example := @ExpressionAtomInternals.proxyExpression_preservesTokenWindow
example := @ExpressionAtomInternals.proxyExpression_preservesTokensOnSuccess
example := @ExpressionAtomInternals.proxyExpression_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.proxyExpression_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.dotConstructor_validFor
example := @ExpressionAtomInternals.dotConstructor_preservesTokenWindow
example := @ExpressionAtomInternals.dotConstructor_preservesTokensOnSuccess
example := @ExpressionAtomInternals.dotConstructor_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.dotConstructor_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.closeTuple_validFor
example := @ExpressionAtomInternals.closeTuple_preservesTokenWindow
example := @ExpressionAtomInternals.closeTuple_preservesTokensOnSuccess
example := @ExpressionAtomInternals.closeTuple_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.closeTuple_preservesOpeningStartOnSuccess
example := @ExpressionAtomInternals.closeTuple_endsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.closeTuple_endsAtLastConsumedTokenOnSuccess
example := @ExpressionAtomInternals.tupleTail_validFor
example := @ExpressionAtomInternals.tupleTail_preservesTokenWindow
example := @ExpressionAtomInternals.tupleTail_preservesTokensOnSuccess
example := @ExpressionAtomInternals.tupleTail_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.tupleTail_preservesOpeningStartOnSuccess
example := @ExpressionAtomInternals.tupleTail_endsAtLastConsumedTokenOnSuccess
example := @ExpressionAtomInternals.parenthesized_validFor
example := @ExpressionAtomInternals.parenthesized_preservesTokenWindow
example := @ExpressionAtomInternals.parenthesized_preservesTokensOnSuccess
example := @ExpressionAtomInternals.parenthesized_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.parenthesized_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.parenthesized_endsAtLastConsumedTokenOnSuccess
example := @ExpressionAtomInternals.arrayLiteral_validFor
example := @ExpressionAtomInternals.arrayLiteral_preservesTokenWindow
example := @ExpressionAtomInternals.arrayLiteral_preservesTokensOnSuccess
example := @ExpressionAtomInternals.arrayLiteral_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.arrayLiteral_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.arrayLiteral_retainsDelimitedEndOnSuccess
example := @ExpressionAtomInternals.optionalLambdaReturnType_validFor
example := @ExpressionAtomInternals.optionalLambdaReturnType_preservesTokenWindow
example := @ExpressionAtomInternals.optionalLambdaReturnType_preservesTokensOnSuccess
example := @ExpressionAtomInternals.optionalLambdaReturnType_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.optionalLambdaReturnType_some_startsAfterArrow
example := @ExpressionAtomInternals.lambdaExpression_preservesTokenWindow
example := @ExpressionAtomInternals.lambdaExpression_preservesTokensOnSuccess
example := @ExpressionAtomInternals.lambdaExpression_cursorMonotoneOnSuccess
example := @ExpressionAtomInternals.lambdaExpression_startsAtCurrentTokenOnSuccess
example := @ExpressionAtomInternals.lambdaExpression_retainsBodyEndOnSuccess

end Tests
