import Solcore.Frontend.LocalReference
import Solcore.Frontend.LocalExpression
import Solcore.Frontend.LocalExpressionTyping
import Solcore.Frontend.LocalFunctionApplication
import Solcore.Frontend.LocalComputation
import Solcore.Frontend.RuntimeComputationFunction
import Solcore.Frontend.DirectWordBinary
import Solcore.Frontend.RecursiveLocalComputation
import Solcore.Frontend.Computation
import Solcore.Frontend.WordMatch
import Solcore.Frontend.RecursiveComputationReturnTree
import Solcore.Frontend.RuntimeInputValidation
import Solcore.Frontend.RuntimeArgumentConstruction
import Solcore.Frontend.RecursiveComputationFunction
import Solcore.Frontend.TypedLetReturnTree
import Solcore.Frontend.LocalExpressionEvaluation
import Solcore.Frontend.LocalExpressionSafetyProperties
import Solcore.Frontend.LocalExpressionExecutionProperties
import Solcore.Frontend.LocalReferenceEmbeddingProperties
import Solcore.Frontend.LocalApplication
import Solcore.Frontend.RuntimeApplicationFunction
import Solcore.Frontend.LocalName
import Solcore.Frontend.LocalExpressionRenaming
import Solcore.Frontend.NumericDigits
import Solcore.Frontend.WordLiteral
import Solcore.Frontend.LocalExpressionEvaluator

/-! Local expression, computation, input, cost, and evaluator fragments. -/
