import Solcore.Frontend.TypeName
import Solcore.Frontend.StructuralType
import Solcore.Frontend.RuntimeFunction
import Solcore.Frontend.RuntimeParameterDeclarations
import Solcore.Frontend.RuntimeParameters
import Solcore.Frontend.ReturnBody
import Solcore.Frontend.RuntimeParameterReferenceProperties
import Solcore.Frontend.LocalTypeInputs
import Solcore.Frontend.Expected
import Solcore.Frontend.LocalApplication
import Solcore.Frontend.GroupedExpectedLambdaArgumentApplication
import Solcore.Frontend.TwoLevelGroupedExpectedLambdaArgumentApplication
import Solcore.Frontend.ThreeOrMoreGroupedExpectedLambdaArgumentApplication
import Solcore.Frontend.ConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.OneLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.TwoLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.ThreeLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.FourLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.FiveLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.SixLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.SevenLevelGroupedConditionalExpectedLambdaArgumentApplication
import Solcore.Frontend.EightOrMoreGroupedConditionalExpectedLambdaArgumentApplication

/-! Type names, runtime adapter inputs, functions, and expected lambdas. -/
