import Solcore.ContractRuntime.RuntimeScalars
import Solcore.ContractRuntime.AddressBytesBE
import Solcore.ContractRuntime.AddressRepresentationCoherence
import Solcore.ContractRuntime.AddressWordBridge
import Solcore.ContractRuntime.FrameOutcome
import Solcore.ContractRuntime.FrameStateResolution
import Solcore.ContractRuntime.FrameRun
import Solcore.ContractRuntime.FrameEffectJournal
import Solcore.ContractRuntime.FrameTrace
import Solcore.ContractRuntime.FrameContinuationContext
import Solcore.ContractRuntime.FrameResolutionResult
import Solcore.ContractRuntime.FrameContinuationContextWithTracePrefix
import Solcore.ContractRuntime.ParentIndexedFrameContinuationContext
import Solcore.ContractRuntime.ParentIndexedFrameContinuationConstruction
import Solcore.ContractRuntime.ParentIndexedFrameTrapRollback
import Solcore.ContractRuntime.ParentIndexedFrameResolutionView
import Solcore.ContractRuntime.ParentIndexedFrameResolutionFold
import Solcore.ContractRuntime.ParentIndexedFrameTrapPropagationPayload
import Solcore.ContractRuntime.RuntimeScalars.TextProperties
import Solcore.ContractRuntime.RuntimeScalars.WordBytesProperties
import Solcore.ContractRuntime.CheckedCoreProgram
import Solcore.ContractRuntime.CheckedHostCoreProgram
import Solcore.ContractRuntime.CheckedHostCoreWordProgram
import Solcore.ContractRuntime.CheckedHostCoreWordCodeSelection
import Solcore.ContractRuntime.HostStorageInputData
import Solcore.ContractRuntime.HostStorageExecutionInputs
import Solcore.ContractRuntime.HostStorageContext
import Solcore.ContractRuntime.HostDriver
import Solcore.ContractRuntime.WordReturnedFrameCompletion
import Solcore.ContractRuntime.HostStorageHandler
import Solcore.ContractRuntime.HostStorageDriver
import Solcore.ContractRuntime.FrameCheckpointedWorkingPairWithPresentStorageAccountCodeExecution
import Solcore.ContractRuntime.FrameCheckpointedWorkingPairWithPresentStorageAccountCodeFrameContinuation
import Solcore.ContractRuntime.WorldState
import Solcore.ContractRuntime.Account
import Solcore.ContractRuntime.WorldStateBalanceProperties
import Solcore.ContractRuntime.WorldStateNonceProperties
import Solcore.ContractRuntime.CreationAddressPolicy
import Solcore.ContractRuntime.CheckedCreationTemplateRegistry
import Solcore.ContractRuntime.ExecutionEnvironment
import Solcore.ContractRuntime.CheckedCoreContract
import Solcore.ContractRuntime.CheckedAccountCreation
import Solcore.ContractRuntime.CheckedCreationPreflight
import Solcore.ContractRuntime.BalanceTransfer
import Solcore.ContractRuntime.WorldStateCode
import Solcore.ContractRuntime.WorldStateWordCodeSelection
import Solcore.ContractRuntime.SelectedCheckedWordExecution
import Solcore.ContractRuntime.ParentIndexedSelectedCheckedWordExecution
import Solcore.ContractRuntime.WorldStateStorageRead
import Solcore.ContractRuntime.FrameCheckpointSnapshot
import Solcore.ContractRuntime.FrameCheckpointedWorkingPair
import Solcore.ContractRuntime.ParentIndexedFrameInitialization
import Solcore.ContractRuntime.FrameCheckpointedWorkingPairWithStorageAddress
import Solcore.ContractRuntime.FrameCheckpointedWorkingPairWithPresentStorageAccount
import Solcore.ContractRuntime.ParentIndexedSelectedExecution
import Solcore.ContractRuntime.FrameContinuationContextFromCheckpointedWorkingPair
import Solcore.ContractRuntime.CoreContractEntryProfile
import Solcore.ContractRuntime.CoreContractEntryProfileProperties
import Solcore.ContractRuntime.TopLevelExecution
import Solcore.ContractRuntime.CoreLanguageResult
import Solcore.ContractRuntime.TopLevelStorageDelta
import Solcore.ContractRuntime.ContractCallFailure
import Solcore.ContractRuntime.ContractWordCallInput
import Solcore.ContractRuntime.CheckedCoreWordOutcome
import Solcore.ContractRuntime.CheckedCoreWordLog
import Solcore.ContractRuntime.TransactionJournal
import Solcore.ContractRuntime.TransactionHostStorage
import Solcore.ContractRuntime.CheckedContractRegistry
import Solcore.ContractRuntime.NestedWordCall
import Solcore.ContractRuntime.WorldStateDelta
import Solcore.ContractRuntime.HostStorageAccountPresence
import Solcore.ContractRuntime.OneLevelNestedTransitionSystem
import Solcore.ContractRuntime.OneLevelNestedExecution
import Solcore.ContractRuntime.BalancedTopLevelExecution

/-!
Umbrella module for checked-Core contract execution. It exposes contract
accounts and world state, host-request handling, transaction and frame state,
nested calls and creation, commit/rollback, and top-level observations together
with their proofs.

This layer is distinct from `Solcore.Core`'s local evaluator and
`Solcore.SourceSemantics`'s source-language judgments.
-/
