import Solcore.Frontend.LocalReference
import Solcore.Frontend.LocalReferenceProperties
import Solcore.Frontend.LocalReferenceElaboration
import Solcore.Frontend.LocalReferenceElaborationProperties
import Solcore.Frontend.LocalReferenceEvaluation
import Solcore.Frontend.LocalReferenceExecutionProperties
import Solcore.Frontend.LocalExpression
import Solcore.Frontend.LocalExpressionResolutionProperties
import Solcore.Frontend.LocalExpressionTyping
import Solcore.Frontend.LocalExpressionTypingProperties
import Solcore.Frontend.LocalExpressionEvaluation
import Solcore.Frontend.LocalExpressionEvaluationProperties
import Solcore.Frontend.LocalExpressionSafetyProperties
import Solcore.Frontend.LocalExpressionExecutionProperties
import Solcore.Frontend.LocalReferenceEmbeddingProperties
import Solcore.Frontend.LocalInputs
import Solcore.Frontend.LocalInputsProperties
import Solcore.Frontend.LocalInputsLookupProperties
import Solcore.Frontend.LocalInputsExecution
import Solcore.Frontend.LocalInputsExecutionProperties
import Solcore.Frontend.LocalNameAvoidance
import Solcore.Frontend.LocalNameAvoidanceProperties
import Solcore.Frontend.LocalInputsExtensionSemantics
import Solcore.Frontend.LocalInputsExtensionProperties
import Solcore.Frontend.LocalExpressionRenamingProperties
import Solcore.Frontend.LocalExpressionRenamingSemantics
import Solcore.Frontend.LocalInputsRenaming
import Solcore.Frontend.LocalInputsRenamingProperties
import Solcore.Frontend.LocalNameRenaming
import Solcore.Frontend.NumericDigits
import Solcore.Frontend.NumericDigitsProperties
import Solcore.Frontend.WordLiteral
import Solcore.Frontend.WordLiteralProperties
import Solcore.Frontend.LocalExpressionCost
import Solcore.Frontend.LocalExpressionCostProperties
import Solcore.Frontend.LocalExpressionCostStepComposition
import Solcore.Frontend.LocalExpressionCostCorrespondence
import Solcore.Frontend.LocalExpressionCostExecutionProperties
import Solcore.Frontend.LocalExpressionCostInvariance
import Solcore.Frontend.LocalInputsCostInvariance
import Solcore.Frontend.TypeName
import Solcore.Frontend.TypeNameProperties
import Solcore.Frontend.RuntimeParameters
import Solcore.Frontend.RuntimeParametersProperties
import Solcore.Frontend.RuntimeParametersLayout
import Solcore.Frontend.ReturnBody
import Solcore.Frontend.ReturnBodyProperties
import Solcore.Frontend.ReturnBodyExecutionProperties
import Solcore.Frontend.ReturnBodyElaboration
import Solcore.Frontend.RuntimeFunctionHeader
import Solcore.Frontend.RuntimeFunctionEntry
import Solcore.Frontend.RuntimeFunctionEntryProperties
import Solcore.Frontend.RuntimeFunctionEntryCost
import Solcore.Frontend.RuntimeFunctionEntryExecutionProperties
import Solcore.Frontend.RuntimeParametersPositionProperties
import Solcore.Frontend.RuntimeParameterReferenceProperties
import Solcore.Frontend.RuntimeFunctionParameterReturnProperties
import Solcore.Frontend.RuntimeParametersStaticProperties
import Solcore.Frontend.RuntimeFunctionStaticProperties

/-!
Canonical explicit-table frontend adapters for local expressions, type names,
runtime parameter inputs, singleton return bodies, and restricted explicit
function entries. Independent source rules
connect to checked Core execution. General source-program resolution, parser
changes, and wire publication are not implied.
-/
