import Solcore.Frontend.LocalReference
import Solcore.Frontend.LocalReferenceProperties
import Solcore.Frontend.LocalReferenceElaboration
import Solcore.Frontend.LocalReferenceElaborationProperties
import Solcore.Frontend.LocalReferenceEvaluation
import Solcore.Frontend.LocalReferenceExecutionProperties
import Solcore.Frontend.LocalExpression
import Solcore.Frontend.LocalExpressionShapeProperties
import Solcore.Frontend.LocalExpressionResolutionProperties
import Solcore.Frontend.LocalExpressionTyping
import Solcore.Frontend.LocalExpressionTypingProperties
import Solcore.Frontend.LocalExpressionEvaluationRules
import Solcore.Frontend.LocalExpressionEvaluation
import Solcore.Frontend.LocalExpressionEvaluationProperties
import Solcore.Frontend.LocalExpressionSafetyProperties
import Solcore.Frontend.LocalExpressionExecutionProperties
import Solcore.Frontend.LocalReferenceEmbeddingProperties
import Solcore.Frontend.LocalInputs
import Solcore.Frontend.LocalInputsProperties
import Solcore.Frontend.LocalInputsLookupProperties
import Solcore.Frontend.LocalInputsExecution
import Solcore.Frontend.LocalInputsExecutionProperties
import Solcore.Frontend.LocalNameAvoidance
import Solcore.Frontend.LocalNameAvoidanceProperties
import Solcore.Frontend.LocalInputsExtensionLookupSupport
import Solcore.Frontend.LocalInputsExtensionTyping
import Solcore.Frontend.LocalInputsExtensionSemantics
import Solcore.Frontend.LocalInputsExtensionProperties
import Solcore.Frontend.LocalExpressionRenamingProperties
import Solcore.Frontend.LocalExpressionRenamingSemantics
import Solcore.Frontend.LocalInputsRenaming
import Solcore.Frontend.LocalInputsRenamingProperties
import Solcore.Frontend.LocalNameRenaming
import Solcore.Frontend.NumericDigits
import Solcore.Frontend.NumericDigitsProperties
import Solcore.Frontend.WordLiteral
import Solcore.Frontend.WordLiteralProperties
import Solcore.Frontend.LocalExpressionCost
import Solcore.Frontend.LocalExpressionCostErasureProperties
import Solcore.Frontend.LocalExpressionCostProperties
import Solcore.Frontend.LocalExpressionCostStepComposition
import Solcore.Frontend.LocalExpressionCostCorrespondence
import Solcore.Frontend.LocalExpressionCostExecutionProperties
import Solcore.Frontend.LocalExpressionCostInvariance
import Solcore.Frontend.LocalInputsCostInvariance
import Solcore.Frontend.TypeName
import Solcore.Frontend.TypeNameProperties
import Solcore.Frontend.TypeNameTableExtensionProperties
import Solcore.Frontend.RuntimeFunctionHeaderTypeExtensionProperties
import Solcore.Frontend.RuntimeParameterDeclarationsTypeExtensionProperties
import Solcore.Frontend.RuntimeFunctionCompilationTypeExtensionProperties
import Solcore.Frontend.RuntimeParameters
import Solcore.Frontend.RuntimeParametersProperties
import Solcore.Frontend.RuntimeParametersLayout
import Solcore.Frontend.ReturnBody
import Solcore.Frontend.ReturnBodyProperties
import Solcore.Frontend.ReturnBodyExecutionProperties
import Solcore.Frontend.ReturnBodyElaboration
import Solcore.Frontend.RuntimeFunctionHeader
import Solcore.Frontend.RuntimeFunctionEntry
import Solcore.Frontend.RuntimeFunctionEntryProperties
import Solcore.Frontend.RuntimeFunctionEntryCost
import Solcore.Frontend.RuntimeFunctionEntryExecutionProperties
import Solcore.Frontend.RuntimeParametersPositionProperties
import Solcore.Frontend.RuntimeParameterReferenceProperties
import Solcore.Frontend.RuntimeFunctionParameterReturnProperties
import Solcore.Frontend.RuntimeParametersStaticProperties
import Solcore.Frontend.RuntimeFunctionStaticProperties
import Solcore.Frontend.RuntimeParametersOwnerProperties
import Solcore.Frontend.RuntimeFunctionOwnerProperties
import Solcore.Frontend.LocalTypeInputs
import Solcore.Frontend.LocalTypeInputsProperties
import Solcore.Frontend.RuntimeParameterDeclarations
import Solcore.Frontend.RuntimeParameterDeclarationsLayout
import Solcore.Frontend.RuntimeParameterDeclarationsPositionProperties
import Solcore.Frontend.RuntimeParameterDeclarationReferenceProperties
import Solcore.Frontend.LocalInputsTypeErasure
import Solcore.Frontend.LocalOwnerRenaming
import Solcore.Frontend.LocalTypeInputsRenaming
import Solcore.Frontend.LocalInputsTypeErasureRenamingProperties
import Solcore.Frontend.RuntimeParameterDeclarationsOwnerProperties
import Solcore.Frontend.RuntimeParameterDeclarationBindingProperties
import Solcore.Frontend.RuntimeFunctionCompilation
import Solcore.Frontend.RuntimeFunctionCompilationProperties
import Solcore.Frontend.RuntimeFunctionCompilationOwnerProperties
import Solcore.Frontend.RuntimeFunctionParameterCompilationProperties
import Solcore.Frontend.RuntimeFunctionConditionalParameterCompilationProperties
import Solcore.Frontend.RuntimeFunctionPreparationFactorization
import Solcore.Frontend.RuntimeFunctionExecutionFactorization
import Solcore.Frontend.RuntimeFunctionCompiledExecutionProperties
import Solcore.Frontend.RuntimeFunctionObservationProperties
import Solcore.Frontend.LocalExpressionStoreProperties
import Solcore.Frontend.RuntimeFunctionStoreProperties
import Solcore.Frontend.LocalExpressionFuelBound
import Solcore.Frontend.LocalExpressionFuelBoundProperties
import Solcore.Frontend.ReturnBodyFuelBoundProperties
import Solcore.Frontend.RuntimeFunctionFuelBoundProperties
import Solcore.Frontend.LocalExpressionResumptionProperties
import Solcore.Frontend.ReturnBodyResumptionProperties
import Solcore.Frontend.RuntimeFunctionResumptionProperties
import Solcore.Resolved.WordLessWithIds
import Solcore.Resolved.WordLessWithIdsEvaluationProperties
import Solcore.Frontend.WordLessCostStepComposition
import Solcore.Core.LocalFragment
import Solcore.Core.LocalFragmentInsertionProperties
import Solcore.Core.LocalFragmentTypingInsertionProperties
import Solcore.Core.LocalFragmentInferenceInsertionProperties
import Solcore.Core.LocalFragmentInsertionPaths
import Solcore.Core.LocalFragmentExactInsertionProperties
import Solcore.Resolved.LocalFragmentProperties
import Solcore.Core.LocalRightWordLessTypingProperties
import Solcore.Core.LocalRightWordLessEvaluationProperties
import Solcore.Frontend.WordLessLocalRightCostProperties
import Solcore.Frontend.ConditionalReturnBody
import Solcore.Frontend.ConditionalReturnBodyProperties
import Solcore.Frontend.ConditionalReturnBodyEvaluation
import Solcore.Frontend.ConditionalReturnBodyEvaluationProperties
import Solcore.Frontend.ReturnBodyContinuationProperties
import Solcore.Frontend.ConditionalReturnBodyExecutionProperties
import Solcore.Frontend.ConditionalReturnBodyRunnerProperties
import Solcore.Frontend.ConditionalReturnBodyFuelBoundProperties
import Solcore.Frontend.ConditionalReturnBodyResumptionProperties
import Solcore.Frontend.TerminalReturnBody
import Solcore.Frontend.TerminalReturnBodyProperties
import Solcore.Frontend.TerminalReturnBodyEvaluation
import Solcore.Frontend.TerminalReturnBodyEvaluationProperties
import Solcore.Frontend.TerminalReturnBodyExecutionProperties
import Solcore.Frontend.TerminalReturnBodyRunnerProperties
import Solcore.Frontend.TerminalReturnBodyFuelBoundProperties
import Solcore.Frontend.TerminalReturnBodyResumptionProperties
import Solcore.Frontend.ReturnBodyRenamingProperties
import Solcore.Frontend.ConditionalReturnBodyRenamingProperties
import Solcore.Frontend.TerminalReturnBodyRenamingProperties
import Solcore.Frontend.ReturnBodyStoreProperties
import Solcore.Frontend.ConditionalReturnBodyStoreProperties
import Solcore.Frontend.TerminalReturnBodyStoreProperties
import Solcore.Frontend.TerminalReturnTree
import Solcore.Frontend.TerminalReturnTreeElaboration
import Solcore.Frontend.TerminalReturnTreeProperties
import Solcore.Frontend.TerminalReturnTreeEmbeddingProperties
import Solcore.Frontend.TerminalReturnTreeEvaluation
import Solcore.Frontend.TerminalReturnTreeEvaluationProperties
import Solcore.Frontend.TerminalReturnTreeExecutionProperties
import Solcore.Frontend.TerminalReturnTreeEvaluationEmbeddingProperties
import Solcore.Frontend.TerminalReturnTreeRunner
import Solcore.Frontend.TerminalReturnTreeRunnerProperties
import Solcore.Frontend.TerminalReturnTreeFuelBoundProperties
import Solcore.Frontend.TerminalReturnTreeResumptionProperties
import Solcore.Frontend.TerminalReturnTreeRunnerEmbeddingProperties
import Solcore.Frontend.TerminalReturnTreeRenamingProperties
import Solcore.Frontend.TerminalReturnTreeStoreProperties
import Solcore.Frontend.TypedLetReturnBody
import Solcore.Frontend.TypedLetReturnBodyElaboration
import Solcore.Frontend.TypedLetReturnBodyProperties
import Solcore.Frontend.TypedLetReturnBodyEmbeddingProperties
import Solcore.Frontend.TypedLetReturnBodyEvaluation
import Solcore.Frontend.TypedLetReturnBodyEvaluationProperties
import Solcore.Frontend.TypedLetReturnBodyExecutionProperties
import Solcore.Frontend.TypedLetReturnBodyEvaluationEmbeddingProperties
import Solcore.Frontend.TypedLetReturnBodyRunner
import Solcore.Frontend.TypedLetReturnBodyRunnerProperties
import Solcore.Frontend.TypedLetReturnBodyFuelBoundProperties
import Solcore.Frontend.TypedLetReturnBodyResumptionProperties
import Solcore.Frontend.TypedLetReturnBodyRunnerEmbeddingProperties
import Solcore.Frontend.TypedLetReturnBodyStoreProperties
import Solcore.Frontend.LocalTypeInputsOwnerProperties
import Solcore.Frontend.TypedLetReturnBodyOwnerProperties
import Solcore.Frontend.TypedLetReturnBodyRunnerOwnerProperties
import Solcore.Frontend.TypedLetReturnBodyTypeExtensionProperties
import Solcore.Frontend.TypedLetReturnBodyRunnerTypeExtensionProperties

/-!
Canonical explicit-table frontend adapters for local expressions, type names,
type-only and runtime parameter inputs, singleton and terminal-conditional return bodies,
and restricted explicit
function entries with value-free compilation. Independent source rules
connect to checked Core execution. General source-program resolution, parser
changes, and wire publication are not implied. Function entries support typed
outer let prefixes before finite terminal if/else trees with singleton-return leaves; compilation owner
invariance requires no runtime argument inhabitants.
Recursive terminal return trees additionally have independent static and
selected-path evaluation/cost semantics with exact Core continuation paths,
a checked body runner, recursive fuel bounds and genuine-state resumption.
Injective identity relabeling retains full results; store replay retains value,
cost and observation thresholds with each result's own store. Existing function
entries reuse these recursive contracts with unchanged headers and parameters.
Typed, initialized, non-shadowing local-declaration prefixes have a separate
value-free static adapter with exact nested Core letE. Independent raw evaluation
and cost correspond to the actual checked Core and exact continuation paths.
A separate checked body runner adds exact fuel thresholds, a source-only bound
and genuine-state resumption. Store replay preserves values and costs, with
each completed or suspended observation retaining its own store. Injective
owner-only relabeling commutes with fresh binding and preserves exact Core,
whole optional results and checkpoints at a fixed store. First-match type-meaning
extension preserves success, and mutual extension also preserves rejection.
Existing function entries reuse the typed-prefix judgments and additive bound,
retaining original parameter records, argument guards and direct Core execution.
No inference, arm-local let or broader binding policy is added.
-/
