import Solcore.Frontend.LocalReference
import Solcore.Frontend.LocalReferenceProperties
import Solcore.Frontend.LocalReferenceElaboration
import Solcore.Frontend.LocalReferenceElaborationProperties
import Solcore.Frontend.LocalReferenceEvaluation
import Solcore.Frontend.LocalReferenceExecutionProperties
import Solcore.Frontend.LocalExpression
import Solcore.Frontend.LocalExpressionResolutionProperties
import Solcore.Frontend.LocalExpressionTyping
import Solcore.Frontend.LocalExpressionTypingProperties
import Solcore.Frontend.LocalExpressionEvaluation
import Solcore.Frontend.LocalExpressionEvaluationProperties
import Solcore.Frontend.LocalExpressionSafetyProperties
import Solcore.Frontend.LocalExpressionExecutionProperties
import Solcore.Frontend.LocalReferenceEmbeddingProperties
import Solcore.Frontend.LocalInputs
import Solcore.Frontend.LocalInputsProperties
import Solcore.Frontend.LocalInputsLookupProperties
import Solcore.Frontend.LocalInputsExecution
import Solcore.Frontend.LocalInputsExecutionProperties
import Solcore.Frontend.LocalNameAvoidance
import Solcore.Frontend.LocalNameAvoidanceProperties
import Solcore.Frontend.LocalInputsExtensionSemantics
import Solcore.Frontend.LocalInputsExtensionProperties
import Solcore.Frontend.LocalExpressionRenamingProperties
import Solcore.Frontend.LocalExpressionRenamingSemantics
import Solcore.Frontend.LocalInputsRenaming
import Solcore.Frontend.LocalInputsRenamingProperties
import Solcore.Frontend.LocalNameRenaming
import Solcore.Frontend.NumericDigits
import Solcore.Frontend.NumericDigitsProperties
import Solcore.Frontend.WordLiteral
import Solcore.Frontend.WordLiteralProperties
import Solcore.Frontend.LocalExpressionCost
import Solcore.Frontend.LocalExpressionCostProperties
import Solcore.Frontend.LocalExpressionCostStepComposition
import Solcore.Frontend.LocalExpressionCostCorrespondence
import Solcore.Frontend.LocalExpressionCostExecutionProperties
import Solcore.Frontend.LocalExpressionCostInvariance
import Solcore.Frontend.LocalInputsCostInvariance
import Solcore.Frontend.TypeName
import Solcore.Frontend.TypeNameProperties
import Solcore.Frontend.RuntimeParameters
import Solcore.Frontend.RuntimeParametersProperties
import Solcore.Frontend.RuntimeParametersLayout

/-!
Canonical local-reference, Boolean/Word, and conditional-expression semantic adapters with
explicit caller-supplied name, type, and runtime tables. Independent source
typing and evaluation correspond exactly to checked Core execution. No source
program resolution, parser change, or wire publication is implied.
-/
