import Solcore.Semantics.RuntimeScalars
import Solcore.Semantics.AddressBytesBE
import Solcore.Semantics.AddressBytesBEProperties
import Solcore.Semantics.AddressRepresentationCoherence
import Solcore.Semantics.AddressWordBridge
import Solcore.Semantics.AddressWordBridgeProperties
import Solcore.Semantics.FrameOutcome
import Solcore.Semantics.FrameOutcomeProperties
import Solcore.Semantics.FrameStateResolution
import Solcore.Semantics.FrameStateResolutionProperties
import Solcore.Semantics.FrameRunResult
import Solcore.Semantics.FrameRunResultProperties
import Solcore.Semantics.FrameEffectJournal
import Solcore.Semantics.FrameEffectJournalProperties
import Solcore.Semantics.FrameTrace
import Solcore.Semantics.FrameTraceProperties
import Solcore.Semantics.FrameTracePrefix
import Solcore.Semantics.FrameTracePrefixProperties
import Solcore.Semantics.FrameRunEffectResolution
import Solcore.Semantics.FrameRunContinuation
import Solcore.Semantics.FrameRunContinuationProperties
import Solcore.Semantics.FrameContinuationContext
import Solcore.Semantics.FrameContinuationContextProperties
import Solcore.Semantics.FrameResolutionResult
import Solcore.Semantics.FrameResolutionResultProperties
import Solcore.Semantics.FrameContinuationContextWithTracePrefix
import Solcore.Semantics.FrameRunEffectResolutionProperties
import Solcore.Semantics.FrameRunEffectCompositionProperties
import Solcore.Semantics.FrameRunEffectTrapPropagationProperties
import Solcore.Semantics.FrameRunEffectContinuationProperties
import Solcore.Semantics.RuntimeScalars.TextProperties
import Solcore.Semantics.RuntimeScalars.WordBytesProperties
import Solcore.Semantics.WorldState
import Solcore.Semantics.WorldStateProperties
import Solcore.Semantics.WorldStateExtensionalityProperties
import Solcore.Semantics.WorldStateUpdateAlgebraProperties
import Solcore.Semantics.WorldStateStorageWriteAlgebraProperties

/-!
Umbrella module for syntax-independent runtime values, observations, and their
proved canonical representations.
-/
